//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoCore.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;+&quot; expected 的本地化字符串。
        /// </summary>
        public static string add_expected {
            get {
                return ResourceManager.GetString("add_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;++&quot; expected 的本地化字符串。
        /// </summary>
        public static string addadd_expected {
            get {
                return ResourceManager.GetString("addadd_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected algorithm not supported 的本地化字符串。
        /// </summary>
        public static string AlgorithmNotSupported {
            get {
                return ResourceManager.GetString("AlgorithmNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;&amp;&quot; expected 的本地化字符串。
        /// </summary>
        public static string and_expected {
            get {
                return ResourceManager.GetString("and_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;&amp;&amp;&quot; expected 的本地化字符串。
        /// </summary>
        public static string andand_expected {
            get {
                return ResourceManager.GetString("andand_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null.
        ///Parameter name: {0} 的本地化字符串。
        /// </summary>
        public static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array with no common superclass not yet supported: {0} 的本地化字符串。
        /// </summary>
        public static string ArrayWithNotSupported {
            get {
                return ResourceManager.GetString("ArrayWithNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;*&quot; expected 的本地化字符串。
        /// </summary>
        public static string asterisk_expected {
            get {
                return ResourceManager.GetString("asterisk_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An attribute argument must be a constant expression 的本地化字符串。
        /// </summary>
        public static string AttributeArgMustBeConstant {
            get {
                return ResourceManager.GetString("AttributeArgMustBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The keyword &apos;base&apos; is expected here to call the base class constructor 的本地化字符串。
        /// </summary>
        public static string BaseIsExpectedToCallBaseConstructor {
            get {
                return ResourceManager.GetString("BaseIsExpectedToCallBaseConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;catch&quot; expected 的本地化字符串。
        /// </summary>
        public static string catch_expected {
            get {
                return ResourceManager.GetString("catch_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 char expected 的本地化字符串。
        /// </summary>
        public static string char_expected {
            get {
                return ResourceManager.GetString("char_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if all the elements in the specified list are of the same type 的本地化字符串。
        /// </summary>
        public static string CheckIfTheElementsInListAreSameType {
            get {
                return ResourceManager.GetString("CheckIfTheElementsInListAreSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if each of rows in multidimensional list has the same number of elements  的本地化字符串。
        /// </summary>
        public static string ChecksIfLengthsAreSameInMultiDimentionalList {
            get {
                return ResourceManager.GetString("ChecksIfLengthsAreSameInMultiDimentionalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if the specified element is present in the specified list 的本地化字符串。
        /// </summary>
        public static string ChecksIfListContainsTheElement {
            get {
                return ResourceManager.GetString("ChecksIfListContainsTheElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if all elements in the specified list are false 的本地化字符串。
        /// </summary>
        public static string ChecksIfTheListIsAllFalse {
            get {
                return ResourceManager.GetString("ChecksIfTheListIsAllFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if all elements in the specified list are true 的本地化字符串。
        /// </summary>
        public static string ChecksIfTheListIsAllTrue {
            get {
                return ResourceManager.GetString("ChecksIfTheListIsAllTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if the list has a uniform depth 的本地化字符串。
        /// </summary>
        public static string ChecksListWithUniformDepth {
            get {
                return ResourceManager.GetString("ChecksListWithUniformDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class declarations are not supported in CodeBlock Nodes, only function definitions and assignment statements 的本地化字符串。
        /// </summary>
        public static string ClassDeclarationNotSupported {
            get {
                return ResourceManager.GetString("ClassDeclarationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;}&quot; expected 的本地化字符串。
        /// </summary>
        public static string closebrace_expected {
            get {
                return ResourceManager.GetString("closebrace_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 closebracket expected 的本地化字符串。
        /// </summary>
        public static string closebracket_expected {
            get {
                return ResourceManager.GetString("closebracket_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;)&apos; expected - Imcomplete Closure 的本地化字符串。
        /// </summary>
        public static string CloseBracketExpected {
            get {
                return ResourceManager.GetString("CloseBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 closeparen expected 的本地化字符串。
        /// </summary>
        public static string closeparen_expected {
            get {
                return ResourceManager.GetString("closeparen_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;,&quot; expected 的本地化字符串。
        /// </summary>
        public static string comma_expected {
            get {
                return ResourceManager.GetString("comma_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if the specified key is present in the specified key-value pair list 的本地化字符串。
        /// </summary>
        public static string ContainsKeys {
            get {
                return ResourceManager.GetString("ContainsKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;~\&quot; expected 的本地化字符串。
        /// </summary>
        public static string curvedash_expected {
            get {
                return ResourceManager.GetString("curvedash_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;--&quot; expected 的本地化字符串。
        /// </summary>
        public static string dashdash_expected {
            get {
                return ResourceManager.GetString("dashdash_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Curly braces are no longer used for list creation. Use square brackets instead, like [] or [1,2,3]. 的本地化字符串。
        /// </summary>
        public static string DeprecatedListInitializationSyntax {
            get {
                return ResourceManager.GetString("DeprecatedListInitializationSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines whether two object instances are equal 的本地化字符串。
        /// </summary>
        public static string DeterminesObjectsAreEqual {
            get {
                return ResourceManager.GetString("DeterminesObjectsAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;/&quot; expected 的本地化字符串。
        /// </summary>
        public static string divider_expected {
            get {
                return ResourceManager.GetString("divider_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;:&quot; expected 的本地化字符串。
        /// </summary>
        public static string doublecolumn_expected {
            get {
                return ResourceManager.GetString("doublecolumn_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty character literal 的本地化字符串。
        /// </summary>
        public static string EmptyCharacterLiteral {
            get {
                return ResourceManager.GetString("EmptyCharacterLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 endline expected 的本地化字符串。
        /// </summary>
        public static string endline_expected {
            get {
                return ResourceManager.GetString("endline_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EOF expected 的本地化字符串。
        /// </summary>
        public static string EOF_expected {
            get {
                return ResourceManager.GetString("EOF_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 equal expected 的本地化字符串。
        /// </summary>
        public static string equal_expected {
            get {
                return ResourceManager.GetString("equal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;=&quot; expected 的本地化字符串。
        /// </summary>
        public static string equalmark_expected {
            get {
                return ResourceManager.GetString("equalmark_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;=&gt;&quot; expected 的本地化字符串。
        /// </summary>
        public static string equalright_expected {
            get {
                return ResourceManager.GetString("equalright_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error 的本地化字符串。
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null value cannot be cast to {0} 的本地化字符串。
        /// </summary>
        public static string FailedToCastFromNull {
            get {
                return ResourceManager.GetString("FailedToCastFromNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert List to Dictionary type. 的本地化字符串。
        /// </summary>
        public static string FailedToConvertArrayToDictionary {
            get {
                return ResourceManager.GetString("FailedToConvertArrayToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import {0} 的本地化字符串。
        /// </summary>
        public static string FailedToImport {
            get {
                return ResourceManager.GetString("FailedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to resolve the comparison function for sorting, expected def sorter : int(x,y) 的本地化字符串。
        /// </summary>
        public static string FailedToResolveSortingFunction {
            get {
                return ResourceManager.GetString("FailedToResolveSortingFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 float expected 的本地化字符串。
        /// </summary>
        public static string float_expected {
            get {
                return ResourceManager.GetString("float_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A function call is not allowed on the left hand side of an assignment 的本地化字符串。
        /// </summary>
        public static string FunctionCallCannotBeAtLeftSide {
            get {
                return ResourceManager.GetString("FunctionCallCannotBeAtLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function dispatch could not be completed {0} 的本地化字符串。
        /// </summary>
        public static string FunctionDispatchFailed {
            get {
                return ResourceManager.GetString("FunctionDispatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No function called {0} on a {1} could be found 的本地化字符串。
        /// </summary>
        public static string FunctionGroupNotFound {
            get {
                return ResourceManager.GetString("FunctionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No function called {0} on a {1} that takes {2} could be found 的本地化字符串。
        /// </summary>
        public static string FunctionGroupWithParameterNotFound {
            get {
                return ResourceManager.GetString("FunctionGroupWithParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets all keys from the specified key-value pair list 的本地化字符串。
        /// </summary>
        public static string GetKeys {
            get {
                return ResourceManager.GetString("GetKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the Type of the current instance 的本地化字符串。
        /// </summary>
        public static string Gettypes {
            get {
                return ResourceManager.GetString("Gettypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets all values stored in the specified key-value pair list and for a simple list it returns all elements in the list 的本地化字符串。
        /// </summary>
        public static string GetValues {
            get {
                return ResourceManager.GetString("GetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 greaterequal expected 的本地化字符串。
        /// </summary>
        public static string greaterequal_expected {
            get {
                return ResourceManager.GetString("greaterequal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 greaterthan expected 的本地化字符串。
        /// </summary>
        public static string greaterthan_expected {
            get {
                return ResourceManager.GetString("greaterthan_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;#&quot; expected 的本地化字符串。
        /// </summary>
        public static string hax_expected {
            get {
                return ResourceManager.GetString("hax_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ident expected 的本地化字符串。
        /// </summary>
        public static string ident_expected {
            get {
                return ResourceManager.GetString("ident_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imports data from a text file containing comma separated values into two-dimensional list 的本地化字符串。
        /// </summary>
        public static string ImportFileByGivenFilePath {
            get {
                return ResourceManager.GetString("ImportFileByGivenFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imports data from a text file containing comma separated values into two-dimensional list and also transpose the output list if specified 的本地化字符串。
        /// </summary>
        public static string ImportFileByGivenFilePathWithMode {
            get {
                return ResourceManager.GetString("ImportFileByGivenFilePathWithMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imports statements are not supported in CodeBlock Nodes, please use the Library UI instead 的本地化字符串。
        /// </summary>
        public static string ImportStatementNotSupported {
            get {
                return ResourceManager.GetString("ImportStatementNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;in&quot; expected 的本地化字符串。
        /// </summary>
        public static string in_expected {
            get {
                return ResourceManager.GetString("in_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No item exists at specified index address 的本地化字符串。
        /// </summary>
        public static string IndexIntoNonArrayObject {
            get {
                return ResourceManager.GetString("IndexIntoNonArrayObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inserts an element into a list at specified index 的本地化字符串。
        /// </summary>
        public static string InsertsAnElementIntoList {
            get {
                return ResourceManager.GetString("InsertsAnElementIntoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_AccessSpecifier 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_AccessSpecifier {
            get {
                return ResourceManager.GetString("invalid_Associative_AccessSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid_Associative_AddOp 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_AddOp {
            get {
                return ResourceManager.GetString("invalid_Associative_AddOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_BinaryOps 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_BinaryOps {
            get {
                return ResourceManager.GetString("invalid_Associative_BinaryOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_BitOp 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_BitOp {
            get {
                return ResourceManager.GetString("invalid_Associative_BitOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_classdecl 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_classdecl {
            get {
                return ResourceManager.GetString("invalid_Associative_classdecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_ComparisonOp 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_ComparisonOp {
            get {
                return ResourceManager.GetString("invalid_Associative_ComparisonOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_DecoratedIdentifier 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_DecoratedIdentifier {
            get {
                return ResourceManager.GetString("invalid_Associative_DecoratedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_Factor 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_Factor {
            get {
                return ResourceManager.GetString("invalid_Associative_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_FunctionalStatement 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_FunctionalStatement {
            get {
                return ResourceManager.GetString("invalid_Associative_FunctionalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_functiondecl 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_functiondecl {
            get {
                return ResourceManager.GetString("invalid_Associative_functiondecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_LanguageBlock 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_LanguageBlock {
            get {
                return ResourceManager.GetString("invalid_Associative_LanguageBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid list@level syntax, consider using @L1 for level 1. 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_Level {
            get {
                return ResourceManager.GetString("invalid_Associative_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_LogicalOp 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_LogicalOp {
            get {
                return ResourceManager.GetString("invalid_Associative_LogicalOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_MulOp 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_MulOp {
            get {
                return ResourceManager.GetString("invalid_Associative_MulOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_NameReference 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_NameReference {
            get {
                return ResourceManager.GetString("invalid_Associative_NameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_negop 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_negop {
            get {
                return ResourceManager.GetString("invalid_Associative_negop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_Number 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_Number {
            get {
                return ResourceManager.GetString("invalid_Associative_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_PostFixOp 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_PostFixOp {
            get {
                return ResourceManager.GetString("invalid_Associative_PostFixOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_Statement 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_Statement {
            get {
                return ResourceManager.GetString("invalid_Associative_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_UnaryExpression 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_UnaryExpression {
            get {
                return ResourceManager.GetString("invalid_Associative_UnaryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Associative_unaryop 的本地化字符串。
        /// </summary>
        public static string invalid_Associative_unaryop {
            get {
                return ResourceManager.GetString("invalid_Associative_unaryop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Hydrogen 的本地化字符串。
        /// </summary>
        public static string invalid_Hydrogen {
            get {
                return ResourceManager.GetString("invalid_Hydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_addop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_addop {
            get {
                return ResourceManager.GetString("invalid_Imperative_addop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_assignstmt 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_assignstmt {
            get {
                return ResourceManager.GetString("invalid_Imperative_assignstmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_bitop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_bitop {
            get {
                return ResourceManager.GetString("invalid_Imperative_bitop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_decoratedIdentifier 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_decoratedIdentifier {
            get {
                return ResourceManager.GetString("invalid_Imperative_decoratedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_factor 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_factor {
            get {
                return ResourceManager.GetString("invalid_Imperative_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_forloop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_forloop {
            get {
                return ResourceManager.GetString("invalid_Imperative_forloop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_functiondecl 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_functiondecl {
            get {
                return ResourceManager.GetString("invalid_Imperative_functiondecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_ifstmt 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_ifstmt {
            get {
                return ResourceManager.GetString("invalid_Imperative_ifstmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_languageblock 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_languageblock {
            get {
                return ResourceManager.GetString("invalid_Imperative_languageblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_logicalop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_logicalop {
            get {
                return ResourceManager.GetString("invalid_Imperative_logicalop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_mulop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_mulop {
            get {
                return ResourceManager.GetString("invalid_Imperative_mulop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_NameReference 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_NameReference {
            get {
                return ResourceManager.GetString("invalid_Imperative_NameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_num 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_num {
            get {
                return ResourceManager.GetString("invalid_Imperative_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_PostFixOp 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_PostFixOp {
            get {
                return ResourceManager.GetString("invalid_Imperative_PostFixOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_relop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_relop {
            get {
                return ResourceManager.GetString("invalid_Imperative_relop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_stmt 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_stmt {
            get {
                return ResourceManager.GetString("invalid_Imperative_stmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_unaryexpr 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_unaryexpr {
            get {
                return ResourceManager.GetString("invalid_Imperative_unaryexpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Imperative_unaryop 的本地化字符串。
        /// </summary>
        public static string invalid_Imperative_unaryop {
            get {
                return ResourceManager.GetString("invalid_Imperative_unaryop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid Import_Statement 的本地化字符串。
        /// </summary>
        public static string invalid_Import_Statement {
            get {
                return ResourceManager.GetString("invalid_Import_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List indices must be numeric. 的本地化字符串。
        /// </summary>
        public static string InvalidArrayIndexType {
            get {
                return ResourceManager.GetString("InvalidArrayIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not an valid function. 的本地化字符串。
        /// </summary>
        public static string InvalidFunction {
            get {
                return ResourceManager.GetString("InvalidFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \&quot;{0}\&quot; is not a valid language block identifier, do you mean \&quot;Associative\&quot; or \&quot;Imperative\&quot;? 的本地化字符串。
        /// </summary>
        public static string InvalidLanguageBlockIdentifier {
            get {
                return ResourceManager.GetString("InvalidLanguageBlockIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax Error: invalid symbol &apos;{0}&apos;. (Did you mean to use Modifier Stack \&quot; =&gt; \&quot;) 的本地化字符串。
        /// </summary>
        public static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File : &apos;{0}&apos; is already imported 的本地化字符串。
        /// </summary>
        public static string kAlreadyImported {
            get {
                return ResourceManager.GetString("kAlreadyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal error, please report: Function could not be found on final dispatch. 的本地化字符串。
        /// </summary>
        public static string kAmbigousMethodDispatch {
            get {
                return ResourceManager.GetString("kAmbigousMethodDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; of argument &apos;{1}&apos; is not defined 的本地化字符串。
        /// </summary>
        public static string kArgumentTypeUndefined {
            get {
                return ResourceManager.GetString("kArgumentTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index is outside the given range 的本地化字符串。
        /// </summary>
        public static string kArrayOverIndexed {
            get {
                return ResourceManager.GetString("kArrayOverIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type conversion would cause array rank reduction. This is not permitted outside of replication. {511ED65F-FB66-4709-BDDA-DCD5E053B87F} 的本地化字符串。
        /// </summary>
        public static string kArrayRankReduction {
            get {
                return ResourceManager.GetString("kArrayRankReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A string must be made up of characters 的本地化字符串。
        /// </summary>
        public static string kAssignNonCharacterToString {
            get {
                return ResourceManager.GetString("kAssignNonCharacterToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;this&apos; is readonly and cannot be assigned to 的本地化字符串。
        /// </summary>
        public static string kAssingToThis {
            get {
                return ResourceManager.GetString("kAssingToThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call the constructor &apos;{0}()&apos; inside itself 的本地化字符串。
        /// </summary>
        public static string kCallingConstructorInConstructor {
            get {
                return ResourceManager.GetString("kCallingConstructorInConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call the constructor &apos;{0}()&apos; on an existing object 的本地化字符串。
        /// </summary>
        public static string KCallingConstructorOnInstance {
            get {
                return ResourceManager.GetString("KCallingConstructorOnInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}.{1}()&apos; is not a static method 的本地化字符串。
        /// </summary>
        public static string kCallingNonStaticMethod {
            get {
                return ResourceManager.GetString("kCallingNonStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}.{1}&apos; is not a static property 的本地化字符串。
        /// </summary>
        public static string kCallingNonStaticProperty {
            get {
                return ResourceManager.GetString("kCallingNonStaticProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt; Runtime warning: {0}\n - \&quot;{1}\&quot; &lt;line: {2}, col: {3}&gt; 的本地化字符串。
        /// </summary>
        public static string kConsoleWarningMessage {
            get {
                return ResourceManager.GetString("kConsoleWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converting an array to {0} would cause array rank reduction and is not permitted 的本地化字符串。
        /// </summary>
        public static string kConvertArrayToNonArray {
            get {
                return ResourceManager.GetString("kConvertArrayToNonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converting a double to an int may lose information 的本地化字符串。
        /// </summary>
        public static string kConvertDoubleToInt {
            get {
                return ResourceManager.GetString("kConvertDoubleToInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asked to convert non-convertible types 的本地化字符串。
        /// </summary>
        public static string kConvertNonConvertibleTypes {
            get {
                return ResourceManager.GetString("kConvertNonConvertibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A cyclic dependency exists between two variables 的本地化字符串。
        /// </summary>
        public static string kCyclicDependency {
            get {
                return ResourceManager.GetString("kCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal error, please report: Dereferencing a non-pointer. 的本地化字符串。
        /// </summary>
        public static string kDeferencingNonPointer {
            get {
                return ResourceManager.GetString("kDeferencingNonPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The exception type &apos;{0}&apos; is not defined 的本地化字符串。
        /// </summary>
        public static string kExceptionTypeUndefined {
            get {
                return ResourceManager.GetString("kExceptionTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \&quot;{0}\&quot; is a keyword, it can&apos;t be used as constructor name 的本地化字符串。
        /// </summary>
        public static string keywordCannotBeUsedAsConstructorName {
            get {
                return ResourceManager.GetString("keywordCannotBeUsedAsConstructorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \&quot;{0}\&quot; is a keyword, but an identifier was expected 的本地化字符串。
        /// </summary>
        public static string keywordCantBeUsedAsIdentifier {
            get {
                return ResourceManager.GetString("keywordCantBeUsedAsIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converting objects to a function pointer is not allowed 的本地化字符串。
        /// </summary>
        public static string kFailToConverToFunction {
            get {
                return ResourceManager.GetString("kFailToConverToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converting other things to null is not allowed 的本地化字符串。
        /// </summary>
        public static string kFailToConverToNull {
            get {
                return ResourceManager.GetString("kFailToConverToNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert objects to function pointers 的本地化字符串。
        /// </summary>
        public static string kFailToConverToPointer {
            get {
                return ResourceManager.GetString("kFailToConverToPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to obtain object &apos;{0}&apos; for &apos;{1}.{2}&apos; 的本地化字符串。
        /// </summary>
        public static string kFFIFailedToObtainObject {
            get {
                return ResourceManager.GetString("kFFIFailedToObtainObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to obtain this object for &apos;{0}.{1}&apos; 的本地化字符串。
        /// </summary>
        public static string kFFIFailedToObtainThisObject {
            get {
                return ResourceManager.GetString("kFFIFailedToObtainThisObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is being cast to &apos;{1}&apos;, but the allowed range is [{2}..{3}] 的本地化字符串。
        /// </summary>
        public static string kFFIInvalidCast {
            get {
                return ResourceManager.GetString("kFFIInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File : &apos;{0}&apos; not found 的本地化字符串。
        /// </summary>
        public static string kFileNotFound {
            get {
                return ResourceManager.GetString("kFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No candidate function could be found 的本地化字符串。
        /// </summary>
        public static string kFunctionNotFound {
            get {
                return ResourceManager.GetString("kFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All paths through the method &apos;{0}()&apos; must return a value 的本地化字符串。
        /// </summary>
        public static string kFunctionNotReturnAtAllCodePaths {
            get {
                return ResourceManager.GetString("kFunctionNotReturnAtAllCodePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index is out of range 的本地化字符串。
        /// </summary>
        public static string kIndexOutOfRange {
            get {
                return ResourceManager.GetString("kIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The amount in range expression should be an positive integer 的本地化字符串。
        /// </summary>
        public static string kInvalidAmountInRangeExpression {
            get {
                return ResourceManager.GetString("kInvalidAmountInRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument is invalid 的本地化字符串。
        /// </summary>
        public static string kInvalidArguments {
            get {
                return ResourceManager.GetString("kInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value used in a range expression must be a number or a letter 的本地化字符串。
        /// </summary>
        public static string kInvalidArgumentsInRangeExpression {
            get {
                return ResourceManager.GetString("kInvalidArgumentsInRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal error, please report: Statement break causes function to abnormally return null. 的本地化字符串。
        /// </summary>
        public static string kInvalidBreakForFunction {
            get {
                return ResourceManager.GetString("kInvalidBreakForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal error, please report: Statement continue cause function to abnormally return null. 的本地化字符串。
        /// </summary>
        public static string kInvalidContinueForFunction {
            get {
                return ResourceManager.GetString("kInvalidContinueForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; cannot be used as list level name, consider using L1 for level 1. 的本地化字符串。
        /// </summary>
        public static string kInvalidListLevelName {
            get {
                return ResourceManager.GetString("kInvalidListLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A cyclic dependency exists between two variables 的本地化字符串。
        /// </summary>
        public static string kInvalidStaticCyclicDependency {
            get {
                return ResourceManager.GetString("kInvalidStaticCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start value can be just number or single letter 的本地化字符串。
        /// </summary>
        public static string kInvalidStringArgumentInRangeExpression {
            get {
                return ResourceManager.GetString("kInvalidStringArgumentInRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;this&apos; can only be used in methods that are members of a class 的本地化字符串。
        /// </summary>
        public static string kInvalidThis {
            get {
                return ResourceManager.GetString("kInvalidThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type is invalid 的本地化字符串。
        /// </summary>
        public static string kInvalidType {
            get {
                return ResourceManager.GetString("kInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range and Sequence expressions support only ASCII characters 的本地化字符串。
        /// </summary>
        public static string kInvalidUnicodeArgumentInRangeExpression {
            get {
                return ResourceManager.GetString("kInvalidUnicodeArgumentInRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}()&apos; is invoked on an invalid object. 的本地化字符串。
        /// </summary>
        public static string kInvokeMethodOnInvalidObject {
            get {
                return ResourceManager.GetString("kInvokeMethodOnInvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}()&apos; is already defined 的本地化字符串。
        /// </summary>
        public static string kMethodAlreadyDefined {
            get {
                return ResourceManager.GetString("kMethodAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; has been deprecated, please use method &apos;{1}&apos; instead 的本地化字符串。
        /// </summary>
        public static string kMethodDeprecated {
            get {
                return ResourceManager.GetString("kMethodDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}()&apos; has some invalid arguments 的本地化字符串。
        /// </summary>
        public static string kMethodHasInvalidArguments {
            get {
                return ResourceManager.GetString("kMethodHasInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}()&apos; can&apos;t be reached from here 的本地化字符串。
        /// </summary>
        public static string kMethodIsInaccessible {
            get {
                return ResourceManager.GetString("kMethodIsInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}()&apos; not found 的本地化字符串。
        /// </summary>
        public static string kMethodNotFound {
            get {
                return ResourceManager.GetString("kMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal error, please report: Method resolution failure on: {0}() 的本地化字符串。
        /// </summary>
        public static string kMethodResolutionFailure {
            get {
                return ResourceManager.GetString("kMethodResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator &apos;{0}&apos; cannot be applied to operands of type &apos;{1}&apos; and &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string kMethodResolutionFailureForOperator {
            get {
                return ResourceManager.GetString("kMethodResolutionFailureForOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no version of {0} that accepts argument type(s) ({1}). 的本地化字符串。
        /// </summary>
        public static string kMethodResolutionFailureWithTypes {
            get {
                return ResourceManager.GetString("kMethodResolutionFailureWithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}()&apos; recursed until Dynamo ran out of memory, please add a base case. 的本地化字符串。
        /// </summary>
        public static string kMethodStackOverflow {
            get {
                return ResourceManager.GetString("kMethodStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple definitions for &apos;{0}&apos; are found as {1} 的本地化字符串。
        /// </summary>
        public static string kMultipleSymbolFound {
            get {
                return ResourceManager.GetString("kMultipleSymbolFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple definitions for &apos;{0}&apos; are found as {1} 的本地化字符串。
        /// </summary>
        public static string kMultipleSymbolFoundFromName {
            get {
                return ResourceManager.GetString("kMultipleSymbolFoundFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No step size is specified in amount range expression 的本地化字符串。
        /// </summary>
        public static string kNoStepSizeInAmountRangeExpression {
            get {
                return ResourceManager.GetString("kNoStepSizeInAmountRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; is inaccessible 的本地化字符串。
        /// </summary>
        public static string kPropertyInaccessible {
            get {
                return ResourceManager.GetString("kPropertyInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; is inaccessible 的本地化字符串。
        /// </summary>
        public static string kPropertyIsInaccessible {
            get {
                return ResourceManager.GetString("kPropertyIsInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; not found 的本地化字符串。
        /// </summary>
        public static string kPropertyNotFound {
            get {
                return ResourceManager.GetString("kPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No property called {0} on {1} could be found 的本地化字符串。
        /// </summary>
        public static string kPropertyOfClassNotFound {
            get {
                return ResourceManager.GetString("kPropertyOfClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An amount operator cannot be used together with a step operator 的本地化字符串。
        /// </summary>
        public static string kRangeExpressionConflictOperator {
            get {
                return ResourceManager.GetString("kRangeExpressionConflictOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The amount of step is invalid. 的本地化字符串。
        /// </summary>
        public static string kRangeExpressionWithInvalidAmount {
            get {
                return ResourceManager.GetString("kRangeExpressionWithInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The step size of range expression is invalid. 的本地化字符串。
        /// </summary>
        public static string kRangeExpressionWithInvalidStepSize {
            get {
                return ResourceManager.GetString("kRangeExpressionWithInvalidStepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The step number of range expression should be greater than 0 的本地化字符串。
        /// </summary>
        public static string kRangeExpressionWithNegativeStepNumber {
            get {
                return ResourceManager.GetString("kRangeExpressionWithNegativeStepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The step number of range expression should be integer 的本地化字符串。
        /// </summary>
        public static string kRangeExpressionWithNonIntegerStepNumber {
            get {
                return ResourceManager.GetString("kRangeExpressionWithNonIntegerStepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The step size of range expression should not be 0 的本地化字符串。
        /// </summary>
        public static string kRangeExpressionWithStepSizeZero {
            get {
                return ResourceManager.GetString("kRangeExpressionWithStepSizeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return type &apos;{0}&apos; of method &apos;{1}()&apos; is not defined 的本地化字符串。
        /// </summary>
        public static string kReturnTypeUndefined {
            get {
                return ResourceManager.GetString("kReturnTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find static method or constructor {0}.{1}() 的本地化字符串。
        /// </summary>
        public static string kStaticMethodNotFound {
            get {
                return ResourceManager.GetString("kStaticMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String indexing cannot be assigned to, it is read only 的本地化字符串。
        /// </summary>
        public static string kStringIndexingCannotBeAssigned {
            get {
                return ResourceManager.GetString("kStringIndexingCannotBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index to string is out of range 的本地化字符串。
        /// </summary>
        public static string kStringIndexOutOfRange {
            get {
                return ResourceManager.GetString("kStringIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String is over indexed 的本地化字符串。
        /// </summary>
        public static string kStringOverIndexed {
            get {
                return ResourceManager.GetString("kStringOverIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not defined 的本地化字符串。
        /// </summary>
        public static string kTypeUndefined {
            get {
                return ResourceManager.GetString("kTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable &apos;{0}&apos; hasn&apos;t been defined yet 的本地化字符串。
        /// </summary>
        public static string kUnboundIdentifierMsg {
            get {
                return ResourceManager.GetString("kUnboundIdentifierMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a static property, so cannot be assigned to static properties or used in static methods. 的本地化字符串。
        /// </summary>
        public static string kUsingNonStaticMemberInStaticContext {
            get {
                return ResourceManager.GetString("kUsingNonStaticMemberInStaticContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;this&apos; cannot be used in static method 的本地化字符串。
        /// </summary>
        public static string kUsingThisInStaticFunction {
            get {
                return ResourceManager.GetString("kUsingThisInStaticFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_break expected 的本地化字符串。
        /// </summary>
        public static string kw_break_expected {
            get {
                return ResourceManager.GetString("kw_break_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_class expected 的本地化字符串。
        /// </summary>
        public static string kw_class_expected {
            get {
                return ResourceManager.GetString("kw_class_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_constructor expected 的本地化字符串。
        /// </summary>
        public static string kw_constructor_expected {
            get {
                return ResourceManager.GetString("kw_constructor_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_continue expected 的本地化字符串。
        /// </summary>
        public static string kw_continue_expected {
            get {
                return ResourceManager.GetString("kw_continue_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_def expected 的本地化字符串。
        /// </summary>
        public static string kw_def_expected {
            get {
                return ResourceManager.GetString("kw_def_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_else expected 的本地化字符串。
        /// </summary>
        public static string kw_else_expected {
            get {
                return ResourceManager.GetString("kw_else_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_elseif expected 的本地化字符串。
        /// </summary>
        public static string kw_elseif_expected {
            get {
                return ResourceManager.GetString("kw_elseif_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_extend expected 的本地化字符串。
        /// </summary>
        public static string kw_extend_expected {
            get {
                return ResourceManager.GetString("kw_extend_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_external expected 的本地化字符串。
        /// </summary>
        public static string kw_external_expected {
            get {
                return ResourceManager.GetString("kw_external_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_for expected 的本地化字符串。
        /// </summary>
        public static string kw_for_expected {
            get {
                return ResourceManager.GetString("kw_for_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_from expected 的本地化字符串。
        /// </summary>
        public static string kw_from_expected {
            get {
                return ResourceManager.GetString("kw_from_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_heap expected 的本地化字符串。
        /// </summary>
        public static string kw_heap_expected {
            get {
                return ResourceManager.GetString("kw_heap_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_if expected 的本地化字符串。
        /// </summary>
        public static string kw_if_expected {
            get {
                return ResourceManager.GetString("kw_if_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_import expected 的本地化字符串。
        /// </summary>
        public static string kw_import_expected {
            get {
                return ResourceManager.GetString("kw_import_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_local expected 的本地化字符串。
        /// </summary>
        public static string kw_local_expected {
            get {
                return ResourceManager.GetString("kw_local_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_native expected 的本地化字符串。
        /// </summary>
        public static string kw_native_expected {
            get {
                return ResourceManager.GetString("kw_native_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_prefix expected 的本地化字符串。
        /// </summary>
        public static string kw_prefix_expected {
            get {
                return ResourceManager.GetString("kw_prefix_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_static expected 的本地化字符串。
        /// </summary>
        public static string kw_static_expected {
            get {
                return ResourceManager.GetString("kw_static_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kw_while expected 的本地化字符串。
        /// </summary>
        public static string kw_while_expected {
            get {
                return ResourceManager.GetString("kw_while_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lessequal expected 的本地化字符串。
        /// </summary>
        public static string lessequal_expected {
            get {
                return ResourceManager.GetString("lessequal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lessthan expected 的本地化字符串。
        /// </summary>
        public static string lessthan_expected {
            get {
                return ResourceManager.GetString("lessthan_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; has been deprecated, please use method &apos;{1}&apos; instead with Dictionary type 的本地化字符串。
        /// </summary>
        public static string ListMethodDeprecated {
            get {
                return ResourceManager.GetString("ListMethodDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 literal_false expected 的本地化字符串。
        /// </summary>
        public static string literal_false_expected {
            get {
                return ResourceManager.GetString("literal_false_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 literal_null expected 的本地化字符串。
        /// </summary>
        public static string literal_null_expected {
            get {
                return ResourceManager.GetString("literal_null_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 literal_true expected 的本地化字符串。
        /// </summary>
        public static string literal_true_expected {
            get {
                return ResourceManager.GetString("literal_true_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maps a vlaue from one range to another range 的本地化字符串。
        /// </summary>
        public static string MapsValueFromOneRangeToAnotherRange {
            get {
                return ResourceManager.GetString("MapsValueFromOneRangeToAnotherRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maps a value into an input range 的本地化字符串。
        /// </summary>
        public static string MapsValueIntoInputRange {
            get {
                return ResourceManager.GetString("MapsValueIntoInputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replication requested exceeds the available dimensions of the array. This case is not yet supported {0} 的本地化字符串。
        /// </summary>
        public static string MaxDimensionExceeded {
            get {
                return ResourceManager.GetString("MaxDimensionExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integer modulo by zero 的本地化字符串。
        /// </summary>
        public static string ModuloByZero {
            get {
                return ResourceManager.GetString("ModuloByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one dominant list is allowed 的本地化字符串。
        /// </summary>
        public static string MoreThanOneDominantList {
            get {
                return ResourceManager.GetString("MoreThanOneDominantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t decide which function to execute. Please provide more specific type information. Possible functions were:  的本地化字符串。
        /// </summary>
        public static string MultipleFunctionsFound {
            get {
                return ResourceManager.GetString("MultipleFunctionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, multiple guides on a single argument that are not in increasing order are not yet supported, please use a for loop instead.  的本地化字符串。
        /// </summary>
        public static string MultipleGuidesNotSupported {
            get {
                return ResourceManager.GetString("MultipleGuidesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 neg expected 的本地化字符串。
        /// </summary>
        public static string neg_expected {
            get {
                return ResourceManager.GetString("neg_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No constructors for Attribute &apos;{0}&apos; takes {1} arguments 的本地化字符串。
        /// </summary>
        public static string NoConstructorForAttribute {
            get {
                return ResourceManager.GetString("NoConstructorForAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} expects argument type(s) ({1}), but was called with ({2}). 的本地化字符串。
        /// </summary>
        public static string NonOverloadMethodResolutionError {
            get {
                return ResourceManager.GetString("NonOverloadMethodResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot import file: &apos;{0}&apos;: No such file or directory 的本地化字符串。
        /// </summary>
        public static string NoSuchFileOrDirectoryToImport {
            get {
                return ResourceManager.GetString("NoSuchFileOrDirectoryToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not expected 的本地化字符串。
        /// </summary>
        public static string not_expected {
            get {
                return ResourceManager.GetString("not_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 notequal expected 的本地化字符串。
        /// </summary>
        public static string notequal_expected {
            get {
                return ResourceManager.GetString("notequal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 number expected 的本地化字符串。
        /// </summary>
        public static string number_expected {
            get {
                return ResourceManager.GetString("number_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns objects that are included in List1 but excluded in List2 的本地化字符串。
        /// </summary>
        public static string ObjectsContainsInList1NotInList2 {
            get {
                return ResourceManager.GetString("ObjectsContainsInList1NotInList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both arguments were expected to be one-dimensional array type! 的本地化字符串。
        /// </summary>
        public static string OneDArrayExpected {
            get {
                return ResourceManager.GetString("OneDArrayExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{&quot; expected 的本地化字符串。
        /// </summary>
        public static string openbrace_expected {
            get {
                return ResourceManager.GetString("openbrace_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 openbracket expected 的本地化字符串。
        /// </summary>
        public static string openbracket_expected {
            get {
                return ResourceManager.GetString("openbracket_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 openparen expected 的本地化字符串。
        /// </summary>
        public static string openparen_expected {
            get {
                return ResourceManager.GetString("openparen_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} operation failed. 的本地化字符串。
        /// </summary>
        public static string OperationFailType1 {
            get {
                return ResourceManager.GetString("OperationFailType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} operation failed. 
        ///{2} 的本地化字符串。
        /// </summary>
        public static string OperationFailType2 {
            get {
                return ResourceManager.GetString("OperationFailType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;||&quot; expected 的本地化字符串。
        /// </summary>
        public static string oror_expected {
            get {
                return ResourceManager.GetString("oror_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 period expected 的本地化字符串。
        /// </summary>
        public static string period_expected {
            get {
                return ResourceManager.GetString("period_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pipe expected 的本地化字符串。
        /// </summary>
        public static string pipe_expected {
            get {
                return ResourceManager.GetString("pipe_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 postfixed replicationguide expected 的本地化字符串。
        /// </summary>
        public static string postfixed_replicationguide_expected {
            get {
                return ResourceManager.GetString("postfixed_replicationguide_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;^&quot; expected 的本地化字符串。
        /// </summary>
        public static string power_expected {
            get {
                return ResourceManager.GetString("power_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;private&quot; expected 的本地化字符串。
        /// </summary>
        public static string private_expected {
            get {
                return ResourceManager.GetString("private_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Produces the set intersection of two sequences 的本地化字符串。
        /// </summary>
        public static string ProducesTheSetIntersection {
            get {
                return ResourceManager.GetString("ProducesTheSetIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Produces the set union of two sequences by using the default equality comparer 的本地化字符串。
        /// </summary>
        public static string ProducesTheSetUnion {
            get {
                return ResourceManager.GetString("ProducesTheSetUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;protected&quot; expected 的本地化字符串。
        /// </summary>
        public static string protected_expected {
            get {
                return ResourceManager.GetString("protected_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;public&quot; expected 的本地化字符串。
        /// </summary>
        public static string public_expected {
            get {
                return ResourceManager.GetString("public_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;?&quot; expected 的本地化字符串。
        /// </summary>
        public static string question_expected {
            get {
                return ResourceManager.GetString("question_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of items in range expression is over limit 的本地化字符串。
        /// </summary>
        public static string RangeExpressionOutOfMemory {
            get {
                return ResourceManager.GetString("RangeExpressionOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rangeop expected 的本地化字符串。
        /// </summary>
        public static string rangeop_expected {
            get {
                return ResourceManager.GetString("rangeop_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;%&quot; expected 的本地化字符串。
        /// </summary>
        public static string reminder_expected {
            get {
                return ResourceManager.GetString("reminder_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes key from list 的本地化字符串。
        /// </summary>
        public static string RemoveKeys {
            get {
                return ResourceManager.GetString("RemoveKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes a copy of array with specified key removed 的本地化字符串。
        /// </summary>
        public static string RemoveKeys1 {
            get {
                return ResourceManager.GetString("RemoveKeys1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes the members of the list which are not members of the specified type 的本地化字符串。
        /// </summary>
        public static string RemovesTheMembersofTheList {
            get {
                return ResourceManager.GetString("RemovesTheMembersofTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reorders the list using the specified indices 的本地化字符串。
        /// </summary>
        public static string ReordersList {
            get {
                return ResourceManager.GetString("ReordersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 replicationguide_postfix expected 的本地化字符串。
        /// </summary>
        public static string replicationguide_postfix_expected {
            get {
                return ResourceManager.GetString("replicationguide_postfix_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Joins two lists into a single list 的本地化字符串。
        /// </summary>
        public static string ReturnsConcatenatingList {
            get {
                return ResourceManager.GetString("ReturnsConcatenatingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns multidimentional list according the rank given 的本地化字符串。
        /// </summary>
        public static string ReturnsListWithRankDepth {
            get {
                return ResourceManager.GetString("ReturnsListWithRankDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns a list with uniform depth as specified by the input depth 的本地化字符串。
        /// </summary>
        public static string ReturnsListWithUniformDepth {
            get {
                return ResourceManager.GetString("ReturnsListWithUniformDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns number of items in the specified list 的本地化字符串。
        /// </summary>
        public static string ReturnsNumberOfItems {
            get {
                return ResourceManager.GetString("ReturnsNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 return statement is not allowed in constructor 的本地化字符串。
        /// </summary>
        public static string ReturnStatementIsNotAllowedInConstructor {
            get {
                return ResourceManager.GetString("ReturnStatementIsNotAllowedInConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the deepest depth of the list 的本地化字符串。
        /// </summary>
        public static string ReturnsTheDeepestDepthOfTheList {
            get {
                return ResourceManager.GetString("ReturnsTheDeepestDepthOfTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the flattened 1D list of the multi-dimensional input list. If the input is a single value, returns that value. 的本地化字符串。
        /// </summary>
        public static string ReturnsTheFlattened1DList {
            get {
                return ResourceManager.GetString("ReturnsTheFlattened1DList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the index of the member in the list 的本地化字符串。
        /// </summary>
        public static string ReturnsTheIndex {
            get {
                return ResourceManager.GetString("ReturnsTheIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the number of  false values in the list 的本地化字符串。
        /// </summary>
        public static string ReturnsTheNumberOfFalseValueInList {
            get {
                return ResourceManager.GetString("ReturnsTheNumberOfFalseValueInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the number of true values in the list 的本地化字符串。
        /// </summary>
        public static string ReturnsTheNumberOfTrueValue {
            get {
                return ResourceManager.GetString("ReturnsTheNumberOfTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is not enough memory to finish the operation. 的本地化字符串。
        /// </summary>
        public static string RunOutOfMemory {
            get {
                return ResourceManager.GetString("RunOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;;&apos; is expected 的本地化字符串。
        /// </summary>
        public static string SemiColonExpected {
            get {
                return ResourceManager.GetString("SemiColonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorts a specified list by the values of its members in either ascending or descending order 的本地化字符串。
        /// </summary>
        public static string SortsListByValue {
            get {
                return ResourceManager.GetString("SortsListByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorts a specified list by values of its members in ascending order 的本地化字符串。
        /// </summary>
        public static string SortsListByValueInAscending {
            get {
                return ResourceManager.GetString("SortsListByValueInAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 textstring expected 的本地化字符串。
        /// </summary>
        public static string textstring_expected {
            get {
                return ResourceManager.GetString("textstring_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this symbol not expected in Associative_NonAssignmentStatement 的本地化字符串。
        /// </summary>
        public static string this_symbo_no_expected_in_Associative_NonAssignmentStatement {
            get {
                return ResourceManager.GetString("this_symbo_no_expected_in_Associative_NonAssignmentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this symbol not expected in Associative_FunctionalStatement 的本地化字符串。
        /// </summary>
        public static string this_symbol_no_expected_in_Associative_FunctionalStatement {
            get {
                return ResourceManager.GetString("this_symbol_no_expected_in_Associative_FunctionalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this symbol not expected in Associative_FunctionalStatement 的本地化字符串。
        /// </summary>
        public static string this_symbol_not_expected_in_Associative_FunctionalStatement {
            get {
                return ResourceManager.GetString("this_symbol_not_expected_in_Associative_FunctionalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this symbol not expected in Associative_FunctionCallStatement 的本地化字符串。
        /// </summary>
        public static string this_symbol_not_expected_in_Associative_FunctionCallStatement {
            get {
                return ResourceManager.GetString("this_symbol_not_expected_in_Associative_FunctionCallStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this symbol not expected in Associative_Statement 的本地化字符串。
        /// </summary>
        public static string this_symbol_not_expected_in_Associative_Statement {
            get {
                return ResourceManager.GetString("this_symbol_not_expected_in_Associative_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this symbol not expected in Import_Statement 的本地化字符串。
        /// </summary>
        public static string this_symbol_not_expected_in_Import_Statement {
            get {
                return ResourceManager.GetString("this_symbol_not_expected_in_Import_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 throw expected 的本地化字符串。
        /// </summary>
        public static string throw_expected {
            get {
                return ResourceManager.GetString("throw_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many characters in character literal 的本地化字符串。
        /// </summary>
        public static string TooManyCharacters {
            get {
                return ResourceManager.GetString("TooManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ??? expected 的本地化字符串。
        /// </summary>
        public static string triquestionmark_expected {
            get {
                return ResourceManager.GetString("triquestionmark_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;try&quot; expected 的本地化字符串。
        /// </summary>
        public static string try_expected {
            get {
                return ResourceManager.GetString("try_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown attribute {0} 的本地化字符串。
        /// </summary>
        public static string UnknownAttribute {
            get {
                return ResourceManager.GetString("UnknownAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; statement can only be used in imperative language block, consider using an inline conditional instead? 的本地化字符串。
        /// </summary>
        public static string UseInlineConditional {
            get {
                return ResourceManager.GetString("UseInlineConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use List.Join node instead 的本地化字符串。
        /// </summary>
        public static string UseListJoinNode {
            get {
                return ResourceManager.GetString("UseListJoinNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; statement can only be used in imperative language block 的本地化字符串。
        /// </summary>
        public static string ValidForImperativeBlockOnly {
            get {
                return ResourceManager.GetString("ValidForImperativeBlockOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable {0} is used in the same statement that you defined it. Recursive dependency is not allowed. 的本地化字符串。
        /// </summary>
        public static string VariableRecursiveReference {
            get {
                return ResourceManager.GetString("VariableRecursiveReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable {0} has been defined in this code block node. You cannot define a variable more than once. 的本地化字符串。
        /// </summary>
        public static string VariableRedifinitionError {
            get {
                return ResourceManager.GetString("VariableRedifinitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot support Longest and shortest zipped collections 的本地化字符串。
        /// </summary>
        public static string ZipAlgorithmError {
            get {
                return ResourceManager.GetString("ZipAlgorithmError", resourceCulture);
            }
        }
    }
}
