//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSCore.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Friday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekFriday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekMonday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saturday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekSaturday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekSunday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thursday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekThursday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuesday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekTuesday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        internal static string EnumDateOfWeekWednesday {
            get {
                return ResourceManager.GetString("EnumDateOfWeekWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Data.ExportCSV node instead 的本地化字符串。
        /// </summary>
        internal static string ExportToCSVObsolete {
            get {
                return ResourceManager.GetString("ExportToCSVObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input value of Math.Factorial cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string FactorialNegativeInt {
            get {
                return ResourceManager.GetString("FactorialNegativeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The return value of Math.Factorial is out of range. 的本地化字符串。
        /// </summary>
        internal static string FactorialOverflow {
            get {
                return ResourceManager.GetString("FactorialOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must provide a center point. 的本地化字符串。
        /// </summary>
        internal static string FindPointsWithinRadiusNullPointMessage {
            get {
                return ResourceManager.GetString("FindPointsWithinRadiusNullPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The search radius cannot be zero. 的本地化字符串。
        /// </summary>
        internal static string FindPointsWithinRadiusSearchRadiusMessage {
            get {
                return ResourceManager.GetString("FindPointsWithinRadiusSearchRadiusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node is obsolete, please use &quot;String from Object&quot; 的本地化字符串。
        /// </summary>
        internal static string FromObjectObsolete {
            get {
                return ResourceManager.GetString("FromObjectObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more input types are not matching. Lists as keys are not supported. 的本地化字符串。
        /// </summary>
        internal static string InvalidKeysErrorMessage {
            get {
                return ResourceManager.GetString("InvalidKeysErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of items does not match the number of keys. 的本地化字符串。
        /// </summary>
        internal static string InvalidKeysLenghtErrorMessage {
            get {
                return ResourceManager.GetString("InvalidKeysLenghtErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use File.FromPath -&gt;  Image.ReadFromFile nodes instead 的本地化字符串。
        /// </summary>
        internal static string LoadImageFromPathObsolete {
            get {
                return ResourceManager.GetString("LoadImageFromPathObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object cannot be null, please provide appropriate value. 的本地化字符串。
        /// </summary>
        internal static string ObjectArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("ObjectArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot construct a quadtree from an empty set of points. 的本地化字符串。
        /// </summary>
        internal static string QuadtreeConstructionEmptyUVSetMessage {
            get {
                return ResourceManager.GetString("QuadtreeConstructionEmptyUVSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Quadtree cannot be constructed from a null set of UVs. 的本地化字符串。
        /// </summary>
        internal static string QuadtreeConstructionNullUVSetMessage {
            get {
                return ResourceManager.GetString("QuadtreeConstructionNullUVSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use File.FromPath -&gt;  Image.ReadFromFile -&gt;  Image.Pixels nodes instead 的本地化字符串。
        /// </summary>
        internal static string ReadImageObsolete {
            get {
                return ResourceManager.GetString("ReadImageObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use File.FromPath -&gt;  File.ReadText nodes instead. 的本地化字符串。
        /// </summary>
        internal static string ReadTextObsolete {
            get {
                return ResourceManager.GetString("ReadTextObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count is out of range! 的本地化字符串。
        /// </summary>
        internal static string StringRemoveCountOutOfRangeMessage {
            get {
                return ResourceManager.GetString("StringRemoveCountOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartIndex is out of range! 的本地化字符串。
        /// </summary>
        internal static string StringRemoveStartIndexOutOfRangeMessage {
            get {
                return ResourceManager.GetString("StringRemoveStartIndexOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not a valid number. 的本地化字符串。
        /// </summary>
        internal static string StringToNumberInvalidNumberMessage {
            get {
                return ResourceManager.GetString("StringToNumberInvalidNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The url cannot be null. 的本地化字符串。
        /// </summary>
        internal static string WebRequestNullUrlMessage {
            get {
                return ResourceManager.GetString("WebRequestNullUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Image.WriteToFile node instead 的本地化字符串。
        /// </summary>
        internal static string WriteImageObsolete {
            get {
                return ResourceManager.GetString("WriteImageObsolete", resourceCulture);
            }
        }
    }
}
