//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoImperative.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoImperative.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Array size overflow 的本地化字符串。
        /// </summary>
        public static string ArraySizeOverflow {
            get {
                return ResourceManager.GetString("ArraySizeOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is a class name, can&apos;t be used as a variable. 的本地化字符串。
        /// </summary>
        public static string ClassNameAsVariableError {
            get {
                return ResourceManager.GetString("ClassNameAsVariableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array declaration expected constant expression 的本地化字符串。
        /// </summary>
        public static string ConstantExpectedInArrayDeclaration {
            get {
                return ResourceManager.GetString("ConstantExpectedInArrayDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \&quot;{0}\&quot;is a function and not allowed as a variable name 的本地化字符串。
        /// </summary>
        public static string FunctionAsVaribleError {
            get {
                return ResourceManager.GetString("FunctionAsVaribleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function pointer is not allowed at binary expression other than assignment. 的本地化字符串。
        /// </summary>
        public static string FunctionPointerNotAllowedAtBinaryExpression {
            get {
                return ResourceManager.GetString("FunctionPointerNotAllowedAtBinaryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 redefinition of identifier &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string IdentifierRedefinition {
            get {
                return ResourceManager.GetString("IdentifierRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variables declared in an outer scope cannot be changed inside an imperative block. 的本地化字符串。
        /// </summary>
        public static string ImperativeSymbolsAreReadOnly {
            get {
                return ResourceManager.GetString("ImperativeSymbolsAreReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 array initializer must be an expression list 的本地化字符串。
        /// </summary>
        public static string InvalidArrayInitializer {
            get {
                return ResourceManager.GetString("InvalidArrayInitializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An imperative language block is declared within an imperative language block. 的本地化字符串。
        /// </summary>
        public static string InvalidNestedImperativeBlock {
            get {
                return ResourceManager.GetString("InvalidNestedImperativeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only identifier or identifier list can appear on the left hand side of assignment. 的本地化字符串。
        /// </summary>
        public static string OnlyIdentifierOrIdentifierListCanBeOnLeftSide {
            get {
                return ResourceManager.GetString("OnlyIdentifierOrIdentifierListCanBeOnLeftSide", resourceCulture);
            }
        }
    }
}
