//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreNodeModels.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreNodeModels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Boolean AND: Returns true only if both of the inputs are true. If either is false, returns false. 的本地化字符串。
        /// </summary>
        public static string AndDescription {
            get {
                return ResourceManager.GetString("AndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result of application. 的本地化字符串。
        /// </summary>
        public static string ApplyPortDataFuncArgToolTip {
            get {
                return ResourceManager.GetString("ApplyPortDataFuncArgToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function to apply. 的本地化字符串。
        /// </summary>
        public static string ApplyPortDataFuncToolTip {
            get {
                return ResourceManager.GetString("ApplyPortDataFuncToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection between a true and false. 的本地化字符串。
        /// </summary>
        public static string BooleanDescription {
            get {
                return ResourceManager.GetString("BooleanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 true;truth;false 的本地化字符串。
        /// </summary>
        public static string BooleanSelectorSearchTags {
            get {
                return ResourceManager.GetString("BooleanSelectorSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Color from the palette 的本地化字符串。
        /// </summary>
        public static string ColorPaletteDescription {
            get {
                return ResourceManager.GetString("ColorPaletteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 color 的本地化字符串。
        /// </summary>
        public static string ColorPaletteSearchTags {
            get {
                return ResourceManager.GetString("ColorPaletteSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get a color given a color range. 的本地化字符串。
        /// </summary>
        public static string ColorRangeDescription {
            get {
                return ResourceManager.GetString("ColorRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A list of colors to include in the range. 的本地化字符串。
        /// </summary>
        public static string ColorRangePortDataColorsToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataColorsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A list of values between 0.0 and 1.0 which position the input colors along the range. 的本地化字符串。
        /// </summary>
        public static string ColorRangePortDataIndicesToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataIndicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected colors. 的本地化字符串。
        /// </summary>
        public static string ColorRangePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A list of values between 0.0 and 1.0. These values are used to look up the color within the range. 的本地化字符串。
        /// </summary>
        public static string ColorRangePortDataValueToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 colorrange; 的本地化字符串。
        /// </summary>
        public static string ColorRangeSearchTags {
            get {
                return ResourceManager.GetString("ColorRangeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combinator 的本地化字符串。
        /// </summary>
        public static string CombinatorPortDataCombToolTip {
            get {
                return ResourceManager.GetString("CombinatorPortDataCombToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combined lists 的本地化字符串。
        /// </summary>
        public static string CombinatorPortDataResultToolTip {
            get {
                return ResourceManager.GetString("CombinatorPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function #0 的本地化字符串。
        /// </summary>
        public static string ComposePortDataFunc0ToolTip {
            get {
                return ResourceManager.GetString("ComposePortDataFunc0ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function #1 的本地化字符串。
        /// </summary>
        public static string ComposePortDataFunc1ToolTip {
            get {
                return ResourceManager.GetString("ComposePortDataFunc1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composed function. 的本地化字符串。
        /// </summary>
        public static string ComposePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ComposePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert between units of measure. 的本地化字符串。
        /// </summary>
        public static string ConversionNodeDescription {
            get {
                return ResourceManager.GetString("ConversionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Index #0 的本地化字符串。
        /// </summary>
        public static string CreateListPortDataIndex0ToolTip {
            get {
                return ResourceManager.GetString("CreateListPortDataIndex0ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A list 的本地化字符串。
        /// </summary>
        public static string CreateListPortDataResultToolTip {
            get {
                return ResourceManager.GetString("CreateListPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a DateTime object from a formatted date and time string. Date and time must be of the format &quot;April 12, 1977 12:00 PM&quot; 的本地化字符串。
        /// </summary>
        public static string DateTimeDescription {
            get {
                return ResourceManager.GetString("DateTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a directory object from a path. 的本地化字符串。
        /// </summary>
        public static string DirectoryFromPathDescription {
            get {
                return ResourceManager.GetString("DirectoryFromPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows you to select a directory on the system to get its path 的本地化字符串。
        /// </summary>
        public static string DirectoryNodeDescription {
            get {
                return ResourceManager.GetString("DirectoryNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a directory object from a path 的本地化字符串。
        /// </summary>
        public static string DirectoryObjectNodeDescription {
            get {
                return ResourceManager.GetString("DirectoryObjectNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to the directory. 的本地化字符串。
        /// </summary>
        public static string DirectoryObjectPortDataPathToolTip {
            get {
                return ResourceManager.GetString("DirectoryObjectPortDataPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory object. 的本地化字符串。
        /// </summary>
        public static string DirectoryObjectPortDataResultToolTip {
            get {
                return ResourceManager.GetString("DirectoryObjectPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows you to select a directory on the system to get its path. 的本地化字符串。
        /// </summary>
        public static string DirectoryPathDescription {
            get {
                return ResourceManager.GetString("DirectoryPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 directorypath;filepath; 的本地化字符串。
        /// </summary>
        public static string DirectoryPathSearchTags {
            get {
                return ResourceManager.GetString("DirectoryPathSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a number. 的本地化字符串。
        /// </summary>
        public static string DoubleInputNodeDescription {
            get {
                return ResourceManager.GetString("DoubleInputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A slider that produces double values. 的本地化字符串。
        /// </summary>
        public static string DoubleSliderDescription {
            get {
                return ResourceManager.GetString("DoubleSliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A slider that produces numeric values. 的本地化字符串。
        /// </summary>
        public static string DoubleSliderNodeDescription {
            get {
                return ResourceManager.GetString("DoubleSliderNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 double;number;float;integer;slider;numberslider; 的本地化字符串。
        /// </summary>
        public static string DoubleSliderSearchTags {
            get {
                return ResourceManager.GetString("DoubleSliderSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected {0} 的本地化字符串。
        /// </summary>
        public static string DropDownPortDataResultToolTip {
            get {
                return ResourceManager.GetString("DropDownPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert;Units;Length;Area;Volume;convertbetweenunits; 的本地化字符串。
        /// </summary>
        public static string DynamoConvertSearchTags {
            get {
                return ResourceManager.GetString("DynamoConvertSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a file object from a path. 的本地化字符串。
        /// </summary>
        public static string FileFromPathDescription {
            get {
                return ResourceManager.GetString("FileFromPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows you to select a file on the system to get its filename 的本地化字符串。
        /// </summary>
        public static string FilenameNodeDescription {
            get {
                return ResourceManager.GetString("FilenameNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a file object from a path. 的本地化字符串。
        /// </summary>
        public static string FileObjectNodeDescription {
            get {
                return ResourceManager.GetString("FileObjectNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to the file. 的本地化字符串。
        /// </summary>
        public static string FileObjectPortDataPathToolTip {
            get {
                return ResourceManager.GetString("FileObjectPortDataPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File object 的本地化字符串。
        /// </summary>
        public static string FileObjectPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FileObjectPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows you to select a file on the system to get its filename. 的本地化字符串。
        /// </summary>
        public static string FilePathDescription {
            get {
                return ResourceManager.GetString("FilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 filepath; 的本地化字符串。
        /// </summary>
        public static string FilePathSearchTags {
            get {
                return ResourceManager.GetString("FilePathSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predicate used to determine if an element is filtered in or out. 的本地化字符串。
        /// </summary>
        public static string FilterPortDataConditionToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataConditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List to filter 的本地化字符串。
        /// </summary>
        public static string FilterPortDataListToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List containing all elements &quot;x&quot; where condition(x) = True 的本地化字符串。
        /// </summary>
        public static string FilterPortDataResultInToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataResultInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List containing all elements &quot;x&quot; where condition(x) = False 的本地化字符串。
        /// </summary>
        public static string FilterPortDataResultOutToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataResultOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluates mathematical formulas. Uses NCalc: http://ncalc.codeplex.com/ 的本地化字符串。
        /// </summary>
        public static string FormulaDescription {
            get {
                return ResourceManager.GetString("FormulaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result of math computation 的本地化字符串。
        /// </summary>
        public static string FormulaPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FormulaPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array of object to be serialized 的本地化字符串。
        /// </summary>
        public static string FromArrayPortDataArrayToolTip {
            get {
                return ResourceManager.GetString("FromArrayPortDataArrayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String representation of the array 的本地化字符串。
        /// </summary>
        public static string FromArrayPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FromArrayPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string.fromarray;tostring;2string;list2string;listtostring;array2string;arraytostring 的本地化字符串。
        /// </summary>
        public static string FromArraySearchTags {
            get {
                return ResourceManager.GetString("FromArraySearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object to be serialized 的本地化字符串。
        /// </summary>
        public static string FromObjectPortDataObjToolTip {
            get {
                return ResourceManager.GetString("FromObjectPortDataObjToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String representation of the object 的本地化字符串。
        /// </summary>
        public static string FromObjectPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FromObjectPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string.fromobject;tostring;2string;number2string;numbertostring 的本地化字符串。
        /// </summary>
        public static string FromObjectSearchTags {
            get {
                return ResourceManager.GetString("FromObjectSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies a function to arguments. 的本地化字符串。
        /// </summary>
        public static string FunctionApplyDescription {
            get {
                return ResourceManager.GetString("FunctionApplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compose multiple functions. 的本地化字符串。
        /// </summary>
        public static string FunctionComposeDescription {
            get {
                return ResourceManager.GetString("FunctionComposeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional statement 的本地化字符串。
        /// </summary>
        public static string IfDescription {
            get {
                return ResourceManager.GetString("IfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A slider that produces integer values. 的本地化字符串。
        /// </summary>
        public static string IntegerSliderDescription {
            get {
                return ResourceManager.GetString("IntegerSliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A slider that produces integer values. 的本地化字符串。
        /// </summary>
        public static string IntegerSliderNodeDescription {
            get {
                return ResourceManager.GetString("IntegerSliderNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 integerslider; 的本地化字符串。
        /// </summary>
        public static string IntegerSliderSearchTags {
            get {
                return ResourceManager.GetString("IntegerSliderSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an obsolete node 的本地化字符串。
        /// </summary>
        public static string LegacyNodeDescription {
            get {
                return ResourceManager.GetString("LegacyNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies a combinator to each pair in the cartesian product of two sequences 的本地化字符串。
        /// </summary>
        public static string ListCartesianProductDescription {
            get {
                return ResourceManager.GetString("ListCartesianProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cross product;crossreference;cross ref; 的本地化字符串。
        /// </summary>
        public static string ListCartesianProductSearchTags {
            get {
                return ResourceManager.GetString("ListCartesianProductSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies a combinator to each element in two sequences 的本地化字符串。
        /// </summary>
        public static string ListCombineDescription {
            get {
                return ResourceManager.GetString("ListCombineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 map multiple;apply over lists;multiple inputs 的本地化字符串。
        /// </summary>
        public static string ListCombineSearchTags {
            get {
                return ResourceManager.GetString("ListCombineSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Makes a new list out of the given inputs 的本地化字符串。
        /// </summary>
        public static string ListCreateDescription {
            get {
                return ResourceManager.GetString("ListCreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Index #{0} 的本地化字符串。
        /// </summary>
        public static string ListCreateInPortToolTip {
            get {
                return ResourceManager.GetString("ListCreateInPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 entwine;listcreate,newlist;makelist;list; 的本地化字符串。
        /// </summary>
        public static string ListCreateSearchTags {
            get {
                return ResourceManager.GetString("ListCreateSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filters a sequence by a given condition such that for an arbitrary element &quot;x,&quot; condition(x) = True or False. 的本地化字符串。
        /// </summary>
        public static string ListFilterDescription {
            get {
                return ResourceManager.GetString("ListFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 screen;dispatch; 的本地化字符串。
        /// </summary>
        public static string ListFilterSearchTags {
            get {
                return ResourceManager.GetString("ListFilterSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs a computation on each element of a list. Does not accumulate results. 的本地化字符串。
        /// </summary>
        public static string ListForEachDescription {
            get {
                return ResourceManager.GetString("ListForEachDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 apply function;void; 的本地化字符串。
        /// </summary>
        public static string ListForEachSearchTags {
            get {
                return ResourceManager.GetString("ListForEachSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies a combinator to each pair resulting from a longest lacing of the input lists. All lists have their last element repeated to match the length of the longest input. 的本地化字符串。
        /// </summary>
        public static string ListLaceLongestDescription {
            get {
                return ResourceManager.GetString("ListLaceLongestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 repeat last; 的本地化字符串。
        /// </summary>
        public static string ListLaceLongestSearchTags {
            get {
                return ResourceManager.GetString("ListLaceLongestSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies a combinator to each pair resulting from a shortest lacing of the input lists. All lists are truncated to the length of the shortest input. 的本地化字符串。
        /// </summary>
        public static string ListLaceShortestDescription {
            get {
                return ResourceManager.GetString("ListLaceShortestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mix;trim end 的本地化字符串。
        /// </summary>
        public static string ListLaceShortestSearchTags {
            get {
                return ResourceManager.GetString("ListLaceShortestSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies a function over all elements of a list, generating a new list from the results. 的本地化字符串。
        /// </summary>
        public static string ListMapDescription {
            get {
                return ResourceManager.GetString("ListMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function;applied;over list;do to each 的本地化字符串。
        /// </summary>
        public static string ListMapSearchTags {
            get {
                return ResourceManager.GetString("ListMapSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reduces a list into a new value by combining each element with an accumulated result. 的本地化字符串。
        /// </summary>
        public static string ListReduceDescription {
            get {
                return ResourceManager.GetString("ListReduceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 accumulate;aggregate;fold 的本地化字符串。
        /// </summary>
        public static string ListReduceSearchTags {
            get {
                return ResourceManager.GetString("ListReduceSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reduces a list into a new value by combining each element with an accumulated result, produces a list of successive reduced values. 的本地化字符串。
        /// </summary>
        public static string ListScanDescription {
            get {
                return ResourceManager.GetString("ListScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 intermediate;maps;folds 的本地化字符串。
        /// </summary>
        public static string ListScanSearchTags {
            get {
                return ResourceManager.GetString("ListScanSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The procedure used to map element 的本地化字符串。
        /// </summary>
        public static string MapPortDataFxToolTip {
            get {
                return ResourceManager.GetString("MapPortDataFxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list to map over. 的本地化字符串。
        /// </summary>
        public static string MapPortDataListToolTip {
            get {
                return ResourceManager.GetString("MapPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapped list 的本地化字符串。
        /// </summary>
        public static string MapPortDataResultToolTip {
            get {
                return ResourceManager.GetString("MapPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input must be numeric. 的本地化字符串。
        /// </summary>
        public static string NumberNodeInputMustBeNumeric {
            get {
                return ResourceManager.GetString("NumberNodeInputMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boolean OR: Returns true if either of the inputs are true. If neither are true, returns false. 的本地化字符串。
        /// </summary>
        public static string OrDescription {
            get {
                return ResourceManager.GetString("OrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False block 的本地化字符串。
        /// </summary>
        public static string PortDataFalseBlockToolTip {
            get {
                return ResourceManager.GetString("PortDataFalseBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 image 的本地化字符串。
        /// </summary>
        public static string PortDataImageToolTip {
            get {
                return ResourceManager.GetString("PortDataImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        public static string PortDataListToolTip {
            get {
                return ResourceManager.GetString("PortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 operand 的本地化字符串。
        /// </summary>
        public static string PortDataOperandToolTip {
            get {
                return ResourceManager.GetString("PortDataOperandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result 的本地化字符串。
        /// </summary>
        public static string PortDataResultToolTip {
            get {
                return ResourceManager.GetString("PortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test block 的本地化字符串。
        /// </summary>
        public static string PortDataTestBlockToolTip {
            get {
                return ResourceManager.GetString("PortDataTestBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True block 的本地化字符串。
        /// </summary>
        public static string PortDataTrueBlockToolTip {
            get {
                return ResourceManager.GetString("PortDataTrueBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variable 的本地化字符串。
        /// </summary>
        public static string PortDataVariableToolTip {
            get {
                return ResourceManager.GetString("PortDataVariableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a sequence of numbers or letters in the specified range. 的本地化字符串。
        /// </summary>
        public static string RangeDescription {
            get {
                return ResourceManager.GetString("RangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 numberrange;numbersequence; 的本地化字符串。
        /// </summary>
        public static string RangeSearchTags {
            get {
                return ResourceManager.GetString("RangeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reductor Function: accepts one item from each list being reduced, and the current accumulated value, result is the new accumulated value. 的本地化字符串。
        /// </summary>
        public static string ReducePortDataReductorToolTip {
            get {
                return ResourceManager.GetString("ReducePortDataReductorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reduced lists 的本地化字符串。
        /// </summary>
        public static string ReducePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ReducePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting accumulated value, to be passed into the first call to the Reductor function. 的本地化字符串。
        /// </summary>
        public static string ReducePortDataSeedToolTip {
            get {
                return ResourceManager.GetString("ReducePortDataSeedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces an object with a given substitute if the original object satisfies a given condition. 的本地化字符串。
        /// </summary>
        public static string ReplaceByConditionDescription {
            get {
                return ResourceManager.GetString("ReplaceByConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 predicate;override;replace if, 的本地化字符串。
        /// </summary>
        public static string ReplaceByConditionSearchTags {
            get {
                return ResourceManager.GetString("ReplaceByConditionSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predicate used to determine if it should be replaced. 的本地化字符串。
        /// </summary>
        public static string ReplacePortDataConditionToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataConditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item to potentially be replaced 的本地化字符串。
        /// </summary>
        public static string ReplacePortDataItemToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object to replace with 的本地化字符串。
        /// </summary>
        public static string ReplacePortDataReplaceWithToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataReplaceWithToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If condition(item) = True, then &quot;replaceWith&quot; is returned. Otherwise &quot;item&quot; is returned unaltered. 的本地化字符串。
        /// </summary>
        public static string ReplacePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reductor Function: accepts one item from each list being reduced, and the current accumulated value, result is the new accumulated value. 的本地化字符串。
        /// </summary>
        public static string ScanPortDataReductorToolTip {
            get {
                return ResourceManager.GetString("ScanPortDataReductorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanned lists 的本地化字符串。
        /// </summary>
        public static string ScanPortDataResultToolTip {
            get {
                return ResourceManager.GetString("ScanPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting accumulated value, to be passed into the first call to the Reductor function. 的本地化字符串。
        /// </summary>
        public static string ScanPortDataSeedToolTip {
            get {
                return ResourceManager.GetString("ScanPortDataSeedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scoped If statement 的本地化字符串。
        /// </summary>
        public static string ScopeIfDescription {
            get {
                return ResourceManager.GetString("ScopeIfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is your Revit display unit settings 的本地化字符串。
        /// </summary>
        public static string SelectFromComboBoxToolTip {
            get {
                return ResourceManager.GetString("SelectFromComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Curve 的本地化字符串。
        /// </summary>
        public static string SelectionEdgeOutputPortName {
            get {
                return ResourceManager.GetString("SelectionEdgeOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Curves 的本地化字符串。
        /// </summary>
        public static string SelectionEdgesOutputPortName {
            get {
                return ResourceManager.GetString("SelectionEdgesOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        public static string SelectionElementOutputPortName {
            get {
                return ResourceManager.GetString("SelectionElementOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elements 的本地化字符串。
        /// </summary>
        public static string SelectionElementsOutputPortName {
            get {
                return ResourceManager.GetString("SelectionElementsOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surface 的本地化字符串。
        /// </summary>
        public static string SelectionFaceOutputPortName {
            get {
                return ResourceManager.GetString("SelectionFaceOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surfaces 的本地化字符串。
        /// </summary>
        public static string SelectionFacesOutputPortName {
            get {
                return ResourceManager.GetString("SelectionFacesOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing selected. 的本地化字符串。
        /// </summary>
        public static string SelectionNodeNothingSelected {
            get {
                return ResourceManager.GetString("SelectionNodeNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select something in the model. 的本地化字符串。
        /// </summary>
        public static string SelectionNodeSugestion {
            get {
                return ResourceManager.GetString("SelectionNodeSugestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Point 的本地化字符串。
        /// </summary>
        public static string SelectionPointOutputPortName {
            get {
                return ResourceManager.GetString("SelectionPointOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Points 的本地化字符串。
        /// </summary>
        public static string SelectionPointsOutputPortName {
            get {
                return ResourceManager.GetString("SelectionPointsOutputPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected elements. 的本地化字符串。
        /// </summary>
        public static string SelectionPortDataResultToolTip {
            get {
                return ResourceManager.GetString("SelectionPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a sequence of numbers. 的本地化字符串。
        /// </summary>
        public static string SequenceDescription {
            get {
                return ResourceManager.GetString("SequenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 numbersequence; 的本地化字符串。
        /// </summary>
        public static string SequenceSearchTags {
            get {
                return ResourceManager.GetString("SequenceSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert an array to a string representation. 的本地化字符串。
        /// </summary>
        public static string StringfromArrayDescription {
            get {
                return ResourceManager.GetString("StringfromArrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert an object to a string representation. 的本地化字符串。
        /// </summary>
        public static string StringfromObjectDescription {
            get {
                return ResourceManager.GetString("StringfromObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a string. 的本地化字符串。
        /// </summary>
        public static string StringInputNodeDescription {
            get {
                return ResourceManager.GetString("StringInputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A numeric value for conversion. 的本地化字符串。
        /// </summary>
        public static string UnitNodeFromPortTooltip {
            get {
                return ResourceManager.GetString("UnitNodeFromPortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A converted numeric value. 的本地化字符串。
        /// </summary>
        public static string UnitNodeToPortToolTip {
            get {
                return ResourceManager.GetString("UnitNodeToPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visualize the output of node. 的本地化字符串。
        /// </summary>
        public static string WatchDescription {
            get {
                return ResourceManager.GetString("WatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previews an image 的本地化字符串。
        /// </summary>
        public static string WatchImageDescription {
            get {
                return ResourceManager.GetString("WatchImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 image;inspect image;pixels;display;panel;watchimage; 的本地化字符串。
        /// </summary>
        public static string WatchImageSearchTags {
            get {
                return ResourceManager.GetString("WatchImageSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visualize the output of node. 的本地化字符串。
        /// </summary>
        public static string WatchNodeDescription {
            get {
                return ResourceManager.GetString("WatchNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 print;output;disply;panel;inspect;debug 的本地化字符串。
        /// </summary>
        public static string WatchNodeSearchTags {
            get {
                return ResourceManager.GetString("WatchNodeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node to evaluate. 的本地化字符串。
        /// </summary>
        public static string WatchPortDataInputToolTip {
            get {
                return ResourceManager.GetString("WatchPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watch contents. 的本地化字符串。
        /// </summary>
        public static string WatchPortDataResultToolTip {
            get {
                return ResourceManager.GetString("WatchPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 print;output;display 的本地化字符串。
        /// </summary>
        public static string WatchSearchTags {
            get {
                return ResourceManager.GetString("WatchSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make a web request given a url. 的本地化字符串。
        /// </summary>
        public static string WebRequestDescription {
            get {
                return ResourceManager.GetString("WebRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The result of the web request. 的本地化字符串。
        /// </summary>
        public static string WebRequestPortDataResultToolTip {
            get {
                return ResourceManager.GetString("WebRequestPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The url for the web request. 的本地化字符串。
        /// </summary>
        public static string WebRequestPortDataUrlToolTip {
            get {
                return ResourceManager.GetString("WebRequestPortDataUrlToolTip", resourceCulture);
            }
        }
    }
}
