//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Arrrrg, ok 的本地化字符串。
        /// </summary>
        public static string ArggOKButton {
            get {
                return ResourceManager.GetString("ArggOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original file &apos;{0}&apos; gets backed up at &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        public static string BackUpOriginalFileMessage {
            get {
                return ResourceManager.GetString("BackUpOriginalFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad identifier syntax: &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string BadIdentifierSyntax {
            get {
                return ResourceManager.GetString("BadIdentifierSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad range syntax: not of format \&quot;start..end[..(increment|#count)]\&quot; 的本地化字符串。
        /// </summary>
        public static string BadRangeSyntax {
            get {
                return ResourceManager.GetString("BadRangeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build sublists from a list using DesignScript range syntax. 的本地化字符串。
        /// </summary>
        public static string BuildSublistsDescription {
            get {
                return ResourceManager.GetString("BuildSublistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download latest version 的本地化字符串。
        /// </summary>
        public static string ButtonDownloadLastest {
            get {
                return ResourceManager.GetString("ButtonDownloadLastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proceed anyway 的本地化字符串。
        /// </summary>
        public static string ButtonProcess {
            get {
                return ResourceManager.GetString("ButtonProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t have 0 step. 的本地化字符串。
        /// </summary>
        public static string CannotHave0Step {
            get {
                return ResourceManager.GetString("CannotHave0Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file cannot be opened 的本地化字符串。
        /// </summary>
        public static string CannotOpenFile {
            get {
                return ResourceManager.GetString("CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clearing workflow... 的本地化字符串。
        /// </summary>
        public static string ClearingWorkflow {
            get {
                return ResourceManager.GetString("ClearingWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clearing workspace... 的本地化字符串。
        /// </summary>
        public static string ClearingWorkSpace {
            get {
                return ResourceManager.GetString("ClearingWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows for DesignScript code to be authored directly 的本地化字符串。
        /// </summary>
        public static string CodeBlockDescription {
            get {
                return ResourceManager.GetString("CodeBlockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows for DesignScript code to be authored directly 的本地化字符串。
        /// </summary>
        public static string CodeBlockNodeDescription {
            get {
                return ResourceManager.GetString("CodeBlockNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 codeblock; 的本地化字符串。
        /// </summary>
        public static string CodeBlockSearchTags {
            get {
                return ResourceManager.GetString("CodeBlockSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of expression at line {0} 的本地化字符串。
        /// </summary>
        public static string CodeBlockTempIdentifierOutputLabel {
            get {
                return ResourceManager.GetString("CodeBlockTempIdentifierOutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composes two single parameter functions into one function. 的本地化字符串。
        /// </summary>
        public static string ComposeFunctionNodeDescription {
            get {
                return ResourceManager.GetString("ComposeFunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Function 的本地化字符串。
        /// </summary>
        public static string ComposeFunctionPortDataFunctionToolTip {
            get {
                return ResourceManager.GetString("ComposeFunctionPortDataFunctionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composed function: g(f(x)) 的本地化字符串。
        /// </summary>
        public static string ComposeFunctionPortDataResultToolTip {
            get {
                return ResourceManager.GetString("ComposeFunctionPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not compress file.  Is the file in use? 的本地化字符串。
        /// </summary>
        public static string CouldNotCompressFile {
            get {
                return ResourceManager.GetString("CouldNotCompressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t get the latest build from S3 的本地化字符串。
        /// </summary>
        public static string CouldNotGetLatestBuild {
            get {
                return ResourceManager.GetString("CouldNotGetLatestBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t get update data from {0} 的本地化字符串。
        /// </summary>
        public static string CouldNotGetUpdateData {
            get {
                return ResourceManager.GetString("CouldNotGetUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not load types. 的本地化字符串。
        /// </summary>
        public static string CouldNotLoadTypes {
            get {
                return ResourceManager.GetString("CouldNotLoadTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not repair 1-node holes 的本地化字符串。
        /// </summary>
        public static string CouldNotRepairOneNodeHoles {
            get {
                return ResourceManager.GetString("CouldNotRepairOneNodeHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR : Could not create connector between {0} and {1}. 的本地化字符串。
        /// </summary>
        public static string CreatingConnectorError {
            get {
                return ResourceManager.GetString("CreatingConnectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom node \&quot;{0}\&quot; could not be initialized. 的本地化字符串。
        /// </summary>
        public static string CustomNodeCouldNotBeInitialized {
            get {
                return ResourceManager.GetString("CustomNodeCouldNotBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance of a Custom Node 的本地化字符串。
        /// </summary>
        public static string CustomNodeDesciption {
            get {
                return ResourceManager.GetString("CustomNodeDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load custom node directory. Do you have permission to access {0}? 的本地化字符串。
        /// </summary>
        public static string CustomNodeFolderLoadFailure {
            get {
                return ResourceManager.GetString("CustomNodeFolderLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom node definition is not loaded! 的本地化字符串。
        /// </summary>
        public static string CustomNodeNotLoaded {
            get {
                return ResourceManager.GetString("CustomNodeNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom nodes 的本地化字符串。
        /// </summary>
        public static string DefaultCustomNodeCategory {
            get {
                return ResourceManager.GetString("DefaultCustomNodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string DefaultHomeWorkspaceName {
            get {
                return ResourceManager.GetString("DefaultHomeWorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default value 的本地化字符串。
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (disabled) 的本地化字符串。
        /// </summary>
        public static string DefaultValueDisabled {
            get {
                return ResourceManager.GetString("DefaultValueDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 some description 的本地化字符串。
        /// </summary>
        public static string DescriptionResource1 {
            get {
                return ResourceManager.GetString("DescriptionResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory not found : {0} 的本地化字符串。
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The virtual machine that powers Dynamo is experiencing some unexpected errors internally and is likely having great difficulties pulling itself together. It is recommended that you save your work now and reload the file. Giving the Dynamo VM a new lease of life can potentially make it feel happier and behave better. 
        ///
        ///If you don&apos;t mind, it would be helpful for you to send us your file. That will make it quicker for us to get these issues fixed. 的本地化字符串。
        /// </summary>
        public static string DisplayEngineFailureMessageDescription {
            get {
                return ResourceManager.GetString("DisplayEngineFailureMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dll Load Exception: 的本地化字符串。
        /// </summary>
        public static string DllLoadException {
            get {
                return ResourceManager.GetString("DllLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download latest version 的本地化字符串。
        /// </summary>
        public static string DownloadLatestButton {
            get {
                return ResourceManager.GetString("DownloadLatestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DesignScript Builtin Functions 的本地化字符串。
        /// </summary>
        public static string DSFunctionNodeDescription {
            get {
                return ResourceManager.GetString("DSFunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A duplicate of the package called {0} was found at {1}.  Ignoring it. 的本地化字符串。
        /// </summary>
        public static string DulicatedPackage {
            get {
                return ResourceManager.GetString("DulicatedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an obsolete node 的本地化字符串。
        /// </summary>
        public static string DummyNodeDescription {
            get {
                return ResourceManager.GetString("DummyNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate migration type registered for {0} 的本地化字符串。
        /// </summary>
        public static string DuplicateMigrationTypeRegistered {
            get {
                return ResourceManager.GetString("DuplicateMigrationTypeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamo is up to date. 的本地化字符串。
        /// </summary>
        public static string DynamoUpToDate {
            get {
                return ResourceManager.GetString("DynamoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} elapsed for loading xml. 的本地化字符串。
        /// </summary>
        public static string ElapsedWhenLoadingXml {
            get {
                return ResourceManager.GetString("ElapsedWhenLoadingXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluation completed in {0} 的本地化字符串。
        /// </summary>
        public static string EvaluationCompleted {
            get {
                return ResourceManager.GetString("EvaluationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception encountered scanning the package directory at {0} 的本地化字符串。
        /// </summary>
        public static string ExceptionEncountered {
            get {
                return ResourceManager.GetString("ExceptionEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get mirror for variable:  {0}; reason: {1}. 的本地化字符串。
        /// </summary>
        public static string FailedToGetMirrorVariable {
            get {
                return ResourceManager.GetString("FailedToGetMirrorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load {0}\n, Exception: {1} 的本地化字符串。
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load custom node: {0}.  Replacing with proxy custom node. 的本地化字符串。
        /// </summary>
        public static string FailedToLoadCustomNode {
            get {
                return ResourceManager.GetString("FailedToLoadCustomNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: The header for the custom node at {0} failed to load.  It will be left out of search. 的本地化字符串。
        /// </summary>
        public static string FailedToLoadHeader {
            get {
                return ResourceManager.GetString("FailedToLoadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load library: {0} 的本地化字符串。
        /// </summary>
        public static string FailedToLoadLibrary {
            get {
                return ResourceManager.GetString("FailedToLoadLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load type from {0}. The type was {1}. 的本地化字符串。
        /// </summary>
        public static string FailedToLoadType {
            get {
                return ResourceManager.GetString("FailedToLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save {0}\n, Exception: {1} 的本地化字符串。
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original file &apos;{0}&apos; gets backed up at &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        public static string FileBackUpLocation {
            get {
                return ResourceManager.GetString("FileBackUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file cannot be opened. 的本地化字符串。
        /// </summary>
        public static string FileCannotBeOpened {
            get {
                return ResourceManager.GetString("FileCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file may not open correctly 的本地化字符串。
        /// </summary>
        public static string FileNotOpenedCorrectly {
            get {
                return ResourceManager.GetString("FileNotOpenedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance of a Custom Node 的本地化字符串。
        /// </summary>
        public static string FunctionDescription {
            get {
                return ResourceManager.GetString("FunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DesignScript Builtin Functions 的本地化字符串。
        /// </summary>
        public static string FunctionNodeDescription {
            get {
                return ResourceManager.GetString("FunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file &apos;{0}&apos; was created in future version &apos;{1}&apos; and may not open correctly in your installed version of Dynamo &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string FutureFileDescription {
            get {
                return ResourceManager.GetString("FutureFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file may not open correctly 的本地化字符串。
        /// </summary>
        public static string FutureFileSummary {
            get {
                return ResourceManager.GetString("FutureFileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Future File 的本地化字符串。
        /// </summary>
        public static string FutureFileTitle {
            get {
                return ResourceManager.GetString("FutureFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goodbye 的本地化字符串。
        /// </summary>
        public static string GoodByeLog {
            get {
                return ResourceManager.GetString("GoodByeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Click here to edit the group title&gt; 的本地化字符串。
        /// </summary>
        public static string GroupDefaultText {
            get {
                return ResourceManager.GetString("GroupDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACTIONS 的本地化字符串。
        /// </summary>
        public static string HeaderAction {
            get {
                return ResourceManager.GetString("HeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE 的本地化字符串。
        /// </summary>
        public static string HeaderCreate {
            get {
                return ResourceManager.GetString("HeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QUERY 的本地化字符串。
        /// </summary>
        public static string HeaderQuery {
            get {
                return ResourceManager.GetString("HeaderQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No identifiers found. 的本地化字符串。
        /// </summary>
        public static string IdentifiersNotFound {
            get {
                return ResourceManager.GetString("IdentifiersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file &apos;{0}&apos; of version &apos;{1}&apos; cannot be opened by this version of Dynamo ({2}) 的本地化字符串。
        /// </summary>
        public static string IncompatibleOfFileAndDynamo {
            get {
                return ResourceManager.GetString("IncompatibleOfFileAndDynamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is the incorrectly formatted library name: 的本地化字符串。
        /// </summary>
        public static string IncorrectlyFormattedNodeLibraryDisplay {
            get {
                return ResourceManager.GetString("IncorrectlyFormattedNodeLibraryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrectly formatted package node library encountered, this may result in a package assembly not being loaded! 的本地化字符串。
        /// </summary>
        public static string IncorrectlyFormattedNodeLibraryWarning {
            get {
                return ResourceManager.GetString("IncorrectlyFormattedNodeLibraryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file &apos;{0}&apos; was created in future version &apos;{1}&apos; and may not open correctly in your installed version of Dynamo &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        public static string IncorrectVersionToOpenFile {
            get {
                return ResourceManager.GetString("IncorrectVersionToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INPUT 的本地化字符串。
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A function parameter, use with custom nodes 的本地化字符串。
        /// </summary>
        public static string InputNodeDescription {
            get {
                return ResourceManager.GetString("InputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variable;argument;parameter 的本地化字符串。
        /// </summary>
        public static string InputNodeSearchTags {
            get {
                return ResourceManager.GetString("InputNodeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder &apos;{0}&apos; does not exist 的本地化字符串。
        /// </summary>
        public static string InvalidCustomNodeFolderWarning {
            get {
                return ResourceManager.GetString("InvalidCustomNodeFolderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid library format. 的本地化字符串。
        /// </summary>
        public static string InvalidLibraryFormat {
            get {
                return ResourceManager.GetString("InvalidLibraryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The start or end of a range is greater than the number of available elements in the list. 的本地化字符串。
        /// </summary>
        public static string InvalidStartOrEndOfRange {
            get {
                return ResourceManager.GetString("InvalidStartOrEndOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build error for library: {0} 的本地化字符串。
        /// </summary>
        public static string LibraryBuildError {
            get {
                return ResourceManager.GetString("LibraryBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library {0} has been loaded. 的本地化字符串。
        /// </summary>
        public static string LibraryHasBeenLoaded {
            get {
                return ResourceManager.GetString("LibraryHasBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library is dumped to \&quot;{0}\&quot;. 的本地化字符串。
        /// </summary>
        public static string LibraryIsDumped {
            get {
                return ResourceManager.GetString("LibraryIsDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find library path: {0}. 的本地化字符串。
        /// </summary>
        public static string LibraryPathCannotBeFound {
            get {
                return ResourceManager.GetString("LibraryPathCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading node definition for &quot;{0}&quot; from: {1} 的本地化字符串。
        /// </summary>
        public static string LoadingNodeDefinition {
            get {
                return ResourceManager.GetString("LoadingNodeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locate in Disk.. 的本地化字符串。
        /// </summary>
        public static string LocateInDisk {
            get {
                return ResourceManager.GetString("LocateInDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} contains a package with a malformed header.  Ignoring it. 的本地化字符串。
        /// </summary>
        public static string MalformedHeaderPackage {
            get {
                return ResourceManager.GetString("MalformedHeaderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHOW MORE ({0}) 的本地化字符串。
        /// </summary>
        public static string MoreButtonTextFormat {
            get {
                return ResourceManager.GetString("MoreButtonTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string MoveLabel {
            get {
                return ResourceManager.GetString("MoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Note 的本地化字符串。
        /// </summary>
        public static string NewNoteString {
            get {
                return ResourceManager.GetString("NewNoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whilst preparing to run, this node encountered a problem. Please talk to the creators of the node, and give them this message: 的本地化字符串。
        /// </summary>
        public static string NodeProblemEncountered {
            get {
                return ResourceManager.GetString("NodeProblemEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No description available 的本地化字符串。
        /// </summary>
        public static string NoDescriptionAvailable {
            get {
                return ResourceManager.GetString("NoDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} contains a package without a header.  Ignoring it. 的本地化字符串。
        /// </summary>
        public static string NoHeaderPackage {
            get {
                return ResourceManager.GetString("NoHeaderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matches found 的本地化字符串。
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 none 的本地化字符串。
        /// </summary>
        public static string NoneString {
            get {
                return ResourceManager.GetString("NoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing is selected. 的本地化字符串。
        /// </summary>
        public static string NothingIsSelectedWarning {
            get {
                return ResourceManager.GetString("NothingIsSelectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a number. 的本地化字符串。
        /// </summary>
        public static string NumberNodeDescription {
            get {
                return ResourceManager.GetString("NumberNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your file &apos;{0}&apos; of version &apos;{1}&apos; cannot be opened by this version of Dynamo ({2}) 的本地化字符串。
        /// </summary>
        public static string ObsoleteFileDescription {
            get {
                return ResourceManager.GetString("ObsoleteFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obsolete File 的本地化字符串。
        /// </summary>
        public static string ObsoleteFileTitle {
            get {
                return ResourceManager.GetString("ObsoleteFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening home workspace {0}... 的本地化字符串。
        /// </summary>
        public static string OpeningHomeWorkspace {
            get {
                return ResourceManager.GetString("OpeningHomeWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error opening the workbench. 的本地化字符串。
        /// </summary>
        public static string OpenWorkbenchError {
            get {
                return ResourceManager.GetString("OpenWorkbenchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error opening the workspace. 的本地化字符串。
        /// </summary>
        public static string OpenWorkspaceError {
            get {
                return ResourceManager.GetString("OpenWorkspaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OUTPUT 的本地化字符串。
        /// </summary>
        public static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A function output, use with custom nodes 的本地化字符串。
        /// </summary>
        public static string OutputNodeDescription {
            get {
                return ResourceManager.GetString("OutputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package was found to be empty and was not installed. 的本地化字符串。
        /// </summary>
        public static string PackageEmpty {
            get {
                return ResourceManager.GetString("PackageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package is too large!  The package must be less than 15 MB! 的本地化字符串。
        /// </summary>
        public static string PackageTooLarge {
            get {
                return ResourceManager.GetString("PackageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified file path is not recognizable as a stable or a daily build 的本地化字符串。
        /// </summary>
        public static string PathNotRegconizableAsStableOrDailyBuild {
            get {
                return ResourceManager.GetString("PathNotRegconizableAsStableOrDailyBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function output 的本地化字符串。
        /// </summary>
        public static string PortDataFunctionOutputToolTip {
            get {
                return ResourceManager.GetString("PortDataFunctionOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input #{0} 的本地化字符串。
        /// </summary>
        public static string PortDataInputToolTip {
            get {
                return ResourceManager.GetString("PortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output #{0} 的本地化字符串。
        /// </summary>
        public static string PortDataOutputToolTip {
            get {
                return ResourceManager.GetString("PortDataOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parameter 的本地化字符串。
        /// </summary>
        public static string PortDataParameterToolTip {
            get {
                return ResourceManager.GetString("PortDataParameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to the file 的本地化字符串。
        /// </summary>
        public static string PortDataPathToFileToolTip {
            get {
                return ResourceManager.GetString("PortDataPathToFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 return value 的本地化字符串。
        /// </summary>
        public static string PortDataReturnValueToolTip {
            get {
                return ResourceManager.GetString("PortDataReturnValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol 的本地化字符串。
        /// </summary>
        public static string PortDataSymbolToolTip {
            get {
                return ResourceManager.GetString("PortDataSymbolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variable 的本地化字符串。
        /// </summary>
        public static string PortDataVariableToolTip {
            get {
                return ResourceManager.GetString("PortDataVariableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of port names does not equal number of port descriptions. 的本地化字符串。
        /// </summary>
        public static string PortsNameDescriptionDoNotEqualWarningMessage {
            get {
                return ResourceManager.GetString("PortsNameDescriptionDoNotEqualWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proceed anyway 的本地化字符串。
        /// </summary>
        public static string ProceedButton {
            get {
                return ResourceManager.GetString("ProceedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python template set to default file 的本地化字符串。
        /// </summary>
        public static string PythonTemplateDefaultFile {
            get {
                return ResourceManager.GetString("PythonTemplateDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python template : no valid template found. 的本地化字符串。
        /// </summary>
        public static string PythonTemplateInvalid {
            get {
                return ResourceManager.GetString("PythonTemplateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python template set to user file 的本地化字符串。
        /// </summary>
        public static string PythonTemplateUserFile {
            get {
                return ResourceManager.GetString("PythonTemplateUserFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range end could not be parsed. 的本地化字符串。
        /// </summary>
        public static string RangeEndCouldNotBeParsed {
            get {
                return ResourceManager.GetString("RangeEndCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use range or approx. identifier on increment field when one has already been used to specify a count. 的本地化字符串。
        /// </summary>
        public static string RangeOrApprIdentifierAlrUsed {
            get {
                return ResourceManager.GetString("RangeOrApprIdentifierAlrUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount of numbers in the sequence
        ///Default value: 10 的本地化字符串。
        /// </summary>
        public static string RangePortDataAmountToolTip {
            get {
                return ResourceManager.GetString("RangePortDataAmountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number or letter to end the sequence at
        ///Default value: 9 的本地化字符串。
        /// </summary>
        public static string RangePortDataEndToolTip {
            get {
                return ResourceManager.GetString("RangePortDataEndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New sequence 的本地化字符串。
        /// </summary>
        public static string RangePortDataSeqToolTip {
            get {
                return ResourceManager.GetString("RangePortDataSeqToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number or letter to start the sequence at
        ///Default value: 0 的本地化字符串。
        /// </summary>
        public static string RangePortDataStartToolTip {
            get {
                return ResourceManager.GetString("RangePortDataStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Space between numbers or letters
        ///Default value: 1 的本地化字符串。
        /// </summary>
        public static string RangePortDataStepToolTip {
            get {
                return ResourceManager.GetString("RangePortDataStepToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range step could not be parsed. 的本地化字符串。
        /// </summary>
        public static string RangeStepCouldNotBeParsed {
            get {
                return ResourceManager.GetString("RangeStepCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range values must be greater than zero. 的本地化字符串。
        /// </summary>
        public static string RangeValuesGreaterThanZero {
            get {
                return ResourceManager.GetString("RangeValuesGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string RemoveLabel {
            get {
                return ResourceManager.GetString("RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requesting version update info... 的本地化字符串。
        /// </summary>
        public static string RequestingVersionUpdate {
            get {
                return ResourceManager.GetString("RequestingVersionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource Property is not String Type 的本地化字符串。
        /// </summary>
        public static string ResourcePropertyIsNotStringTypeMessage {
            get {
                return ResourceManager.GetString("ResourcePropertyIsNotStringTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource Type does not have Property 的本地化字符串。
        /// </summary>
        public static string ResourceTypeDoesNotHavePropertyMessage {
            get {
                return ResourceManager.GetString("ResourceTypeDoesNotHavePropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run whenever an input to the graph is updated. 的本地化字符串。
        /// </summary>
        public static string RunTypeToolTipAutomatically {
            get {
                return ResourceManager.GetString("RunTypeToolTipAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run when you click the Run button. 的本地化字符串。
        /// </summary>
        public static string RunTypeToolTipManually {
            get {
                return ResourceManager.GetString("RunTypeToolTipManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Periodic is only available when there are nodes in the graph that support periodic update. 的本地化字符串。
        /// </summary>
        public static string RunTypeToolTipPeriodicallyDisabled {
            get {
                return ResourceManager.GetString("RunTypeToolTipPeriodicallyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run at the specified interval. 的本地化字符串。
        /// </summary>
        public static string RunTypeToolTipPeriodicallyEnabled {
            get {
                return ResourceManager.GetString("RunTypeToolTipPeriodicallyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving {0} ... 的本地化字符串。
        /// </summary>
        public static string SavingInProgress {
            get {
                return ResourceManager.GetString("SavingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string SearchTextBlockText {
            get {
                return ResourceManager.GetString("SearchTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a string. 的本地化字符串。
        /// </summary>
        public static string StringNodeDescription {
            get {
                return ResourceManager.GetString("StringNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sublists. 的本地化字符串。
        /// </summary>
        public static string SublistPortDataResultToolTip {
            get {
                return ResourceManager.GetString("SublistPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list from which to create sublists. 的本地化字符串。
        /// </summary>
        public static string SublistsPortDataListToolTip {
            get {
                return ResourceManager.GetString("SublistsPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The offset to apply to the sub-list. Ex. The range &quot;0..2&quot; with an offset of 1 will yield sublists {0,1,2}{1,2,3}{2,3,4}... 的本地化字符串。
        /// </summary>
        public static string SublistsPortDataOffsetToolTip {
            get {
                return ResourceManager.GetString("SublistsPortDataOffsetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Bug To Github 的本地化字符串。
        /// </summary>
        public static string SubmitBugButton {
            get {
                return ResourceManager.GetString("SubmitBugButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Bug To Github 的本地化字符串。
        /// </summary>
        public static string SubmitBugToGithub {
            get {
                return ResourceManager.GetString("SubmitBugToGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A function parameter, use with custom nodes.
        ///
        ///You can specify the type and default value for parameter. E.g.,
        ///
        ///input : var[]..[]
        ///value : bool = false 的本地化字符串。
        /// </summary>
        public static string SymbolNodeDescription {
            get {
                return ResourceManager.GetString("SymbolNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variable;argument;parameter 的本地化字符串。
        /// </summary>
        public static string SymbolSearchTags {
            get {
                return ResourceManager.GetString("SymbolSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Output 的本地化字符串。
        /// </summary>
        public static string ToolTipForTempVar {
            get {
                return ResourceManager.GetString("ToolTipForTempVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function output 的本地化字符串。
        /// </summary>
        public static string ToolTipFunctionOutput {
            get {
                return ResourceManager.GetString("ToolTipFunctionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input # 的本地化字符串。
        /// </summary>
        public static string ToolTipInput {
            get {
                return ResourceManager.GetString("ToolTipInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output # 的本地化字符串。
        /// </summary>
        public static string ToolTipOutput {
            get {
                return ResourceManager.GetString("ToolTipOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 return value 的本地化字符串。
        /// </summary>
        public static string ToolTipReturnValue {
            get {
                return ResourceManager.GetString("ToolTipReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol 的本地化字符串。
        /// </summary>
        public static string ToolTipSymbol {
            get {
                return ResourceManager.GetString("ToolTipSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Result 的本地化字符串。
        /// </summary>
        public static string TopResult {
            get {
                return ResourceManager.GetString("TopResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create instance of custom node with id: \&quot; 的本地化字符串。
        /// </summary>
        public static string UnableToCreateCustomNodeID {
            get {
                return ResourceManager.GetString("UnableToCreateCustomNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled exception in Dynamo engine 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionInDynamoEngine {
            get {
                return ResourceManager.GetString("UnhandledExceptionInDynamoEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled exception in Dynamo engine 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionSummary {
            get {
                return ResourceManager.GetString("UnhandledExceptionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Exception 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This graph currently contains some unresolved nodes, and cannot be saved until the nodes are resolved. If the graph is saved using SaveAs - the unresolved nodes will be removed from the file. 的本地化字符串。
        /// </summary>
        public static string UnresolvedNodesWarningMessage {
            get {
                return ResourceManager.GetString("UnresolvedNodesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This graph cannot be saved until unresolved nodes are removed or resolved. 的本地化字符串。
        /// </summary>
        public static string UnresolvedNodesWarningShortMessage {
            get {
                return ResourceManager.GetString("UnresolvedNodesWarningShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph Contains Unresolved Nodes and Cannot Be Saved. 的本地化字符串。
        /// </summary>
        public static string UnresolvedNodesWarningTitle {
            get {
                return ResourceManager.GetString("UnresolvedNodesWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update available: {0} 的本地化字符串。
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update download complete. 的本地化字符串。
        /// </summary>
        public static string UpdateDownloadComplete {
            get {
                return ResourceManager.GetString("UpdateDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update download progress: {0}% 的本地化字符串。
        /// </summary>
        public static string UpdateDownloadProgress {
            get {
                return ResourceManager.GetString("UpdateDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update download started... 的本地化字符串。
        /// </summary>
        public static string UpdateDownloadStarted {
            get {
                return ResourceManager.GetString("UpdateDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uh oh...
        /// We&apos;re sorry - we tried to save your decisions, but something went wrong. The decision probably hasn&apos;t been saved. This really shouldn&apos;t have happened. Please get in touch via GitHub and send us this information.
        ///You can also try deleting [FILEPATH] and trying again.
        ///Depending on your previous choice, instrumentation may still be running, if you&apos;re worried about this, please consider not using Dynamo until we&apos;ve got back to you to solve the problem.
        ///Sorry about that. 的本地化字符串。
        /// </summary>
        public static string UsageReportingErrorMessage {
            get {
                return ResourceManager.GetString("UsageReportingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string WarningCannotFindType {
            get {
                return ResourceManager.GetString("WarningCannotFindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input.
        ///
        ///The name of parameter should start with alphabetic character. You can specify its type and default value. E.g., 
        ///
        ///input : var[]..[]
        ///value: bool = false 的本地化字符串。
        /// </summary>
        public static string WarningInvalidInput {
            get {
                return ResourceManager.GetString("WarningInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only comments and single variable are allowed in output node. 的本地化字符串。
        /// </summary>
        public static string WarningInvalidOutput {
            get {
                return ResourceManager.GetString("WarningInvalidOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your code goes here 的本地化字符串。
        /// </summary>
        public static string WatermarkLabelText {
            get {
                return ResourceManager.GetString("WatermarkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Dynamo! 的本地化字符串。
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workbench could not be opened. 的本地化字符串。
        /// </summary>
        public static string WorkbenchNotOpen {
            get {
                return ResourceManager.GetString("WorkbenchNotOpen", resourceCulture);
            }
        }
    }
}
